window.sData = {
  "name": "S. JUNGLE ASSAULT",
  "num_decks": 2,
  "first_player": "Attacker",
  "treated_as_cower_cards": [
    "PILLBOX",
    "MINEFIELD"
  ],
  "remove_when_used": null,
  "discard_when_drawn": null,
  "victory_condition": "CONTROL_PERSONALITIES_LOCATION_IMMEDIATE",
  "victory_condition_context_num": 4,
  "victory_condition_context_rr": 5,
  "germany_cards_attacker": null,
  "america_cards_attacker": [ 1, 2, 3, 4, 5, 7, 8, 9, 11, 12, 16, 17, 19 ],
  "russia_cards_attacker": null,
  "japan_cards_attacker": [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 22, 23, 27 ],
  "britian_cards_attacker": [ 1, 3, 4, 5, 6, 7, 8, 14, 16, 22, 23 ],
  "france_cards_attacker": null,
  "italy_cards_attacker": null,
  "finland_cards_attacker": null,
  "germany_cards_defender": null,
  "america_cards_defender": [ 4, 5, 7, 8, 9, 11, 15, 42, 43 ],
  "russia_cards_defender": null,
  "japan_cards_defender": [ 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 16, 21, 25 ],
  "britian_cards_defender": [ 1, 2, 4, 5, 6, 7, 8, 9, 10, 13 ],
  "france_cards_defender": null,
  "italy_cards_defender": null,
  "finland_cards_defender": null
};