window.tutorialData = {
  "name": "Tutorial",
  "num_decks": 2,
  "first_player": "Axis",
  "treated_as_cower_cards": null,
  "remove_when_used": null,
  "discard_when_drawn": [
    "PILLBOX",
    "MINEFIELD",
    "SNIPER",
    "HERO",
    "WIRE",
    "SMOKE"
  ],
  "victory_condition": "LEAST_ELIMINATED",
  "victory_condition_context_num": -1,
  "victory_condition_context_rr": -1,
  "germany_cards_attacker": [
    1,
    2,
    4,
    5,
    6,
    7,
    8,
    9,
    10
  ],
  "america_cards_attacker": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9
  ],
  "russia_cards_attacker": null,
  "japan_cards_attacker": null,
  "britian_cards_attacker": null,
  "france_cards_attacker": null,
  "italy_cards_attacker": null,
  "finland_cards_attacker": null,
  "germany_cards_defender": null,
  "america_cards_defender": null,
  "russia_cards_defender": null,
  "japan_cards_defender": null,
  "britian_cards_defender": null,
  "france_cards_defender": null,
  "italy_cards_defender": null,
  "finland_cards_defender": null
};