window.americaData = {
  "name": "America",
  "hand_capacity": 6,
  "discard": 2,
  "discard_condition_no_action": true,
  "notes": "May discard up to 2 cards on Player.",
  "broken_squad": 50,
  "nationalTactics": {
    "priorityModifiers": {
      "FIRE_OPP": 1.1,             // Firepower doctrine
      "FIRE_HIGH_OPP": 1.2,        // Superior equipment
      "RALLY_ALL": 1.1,            // Good morale
      "MOVE_CAUTIOUS": 1.1,        // Combined arms advance
      "LAY_SMOKE": 1.2,            // Smoke tactics
      "FIX_WEAPON": 1.2,           // Equipment reliability
      "ACQUIRE_WEAPON": 1.1        // Weapon flexibility
    },
    "description": "American tactics emphasize firepower superiority, careful advances with smoke, and equipment maintenance."
  },
  "units": [
    {
      "num": 1,
      "name": "SGT BURNETT",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 4,
      "sl": true,
      "asl": false,
      "weapon": "M1 Thompson",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "morale": 4,
      "points": 47,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 6
    },
    {
      "num": 2,
      "name": "CPL MOORES",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": true,
      "weapon": "M1 Thompson",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "morale": 3,
      "points": 36,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 5
    },
    {
      "num": 3,
      "name": "PFC FOX",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Bar M1918A2",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 3,
      "fp_range_3": 4,
      "fp_range_4": 4,
      "fp_range_5": 5,
      "morale": 4,
      "points": 44,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5
    },
    {
      "num": 4,
      "name": "PVT MCELROY",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "M1 Garand",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 16,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 5
    },
    {
      "num": 5,
      "name": "PVT FRATTALI",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "M1 Garand",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 14,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4
    },
    {
      "num": 6,
      "name": "PVT SMITH",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "M1 Garand",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 1,
      "points": 5, // Original had 5, Card #10 has PT 4. Keeping original 5 for Smith.
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": 3
    },
    {
      "num": 7,
      "name": "PVT ANDERSON",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "M1 Garand",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 14,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4
    },
    {
      "num": 8,
      "name": "PVT BURKE",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "M1 Garand",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 2,
      "points": 9,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 3
    },
    {
      "num": 9,
      "name": "PVT MYERS",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "M1 Garand",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 5,
      "points": 24,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": 6
    },
    {
      "num": 10,
      "name": "PVT WATSON",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "M1 Garand",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 1,
      "points": 4,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": 2
    },
    {
      "num": 11,
      "name": "PVT GREENWOOD",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "M1 Garand",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 16,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 5
    },
     {
      "num": 12,
      "name": "PVT EDWARDS",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "M1 Garand",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 2,
      "points": 11,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 4
    },
     {
      "num": 13,
      "name": "PFC SPOULOS",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "M1 Bazooka 2.36\"",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
      "weapon_details": {
           "type": "Bazooka",
           "range_3_th": "0-1 [2]",
           "range_4_th": "0-2 [0]",
           "range_5_th": "0-3 [0-1]",
           "no_moving_fire": true,
           "ammo": 2
       },
      "morale": 3,
      "points": 52,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "Available 6/1942-1945. No Secondary Weapons Allowed. Breakdown notation: [X3-6] X4-6."
    },
    {
      "num": 14,
      "name": "PFC TOWLE",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "M1 Bazooka 2.36\"",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
       "weapon_details": {
           "type": "Bazooka",
           "range_3_th": "0-1 [1]",
           "range_4_th": "0-2 [0]",
           "range_5_th": "0-3 [0-1]",
           "no_moving_fire": true,
           "ammo": 3
       },
      "morale": 4,
      "points": 74,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 6,
      "notes": "Available 1945. No Secondary Weapons Allowed. Breakdown notation: [X3-6] X4-6."
    },
     {
      "num": 15,
      "name": "PFC NIXON",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Browning M1919A6 .30 calibre",
      "breakdown": 6,
      "fp_range_0": 7,
      "fp_range_1": 8,
      "fp_range_2": 9,
      "fp_range_3": 10,
      "fp_range_4": 11,
      "fp_range_5": 12,
      "weapon_details": {
           "type": "MMG",
           "sustained_fp_0": 3,
           "sustained_fp_1": 4,
           "sustained_fp_2": 4,
           "sustained_fp_3": 5,
           "sustained_fp_4": 5,
           "sustained_fp_5": 6
       },
      "morale": 4,
      "points": 115,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 6,
      "notes": "No Secondary Weapons Allowed. No Moving Fire. Breakdown notation: [X5-6] X6."
    },
     {
      "num": 16,
      "name": "PFC MORAS",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "M2-2 Flamethrower",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 12,
      "weapon_details": {
           "type": "Flamethrower",
           "range": 5,
           "fp": 12,
           "no_def_tem": true,
           "no_ff_inf_bonus": true,
           "moving_fire_not_halved": true,
           "ammo": null
       },
      "morale": 4,
      "points": 73,
      "kia_unpinned": 7,
      "panic": 6,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 8,
      "rout": 6,
      "notes": "No Secondary Weapons Allowed. Breakdown notation: X5-6."
    },
    {
      "num": 17,
      "name": "PFC RANSOM",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "M1 .3 Calibre Carbine",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 3,
      "fp_range_5": 4,
      "morale": 3,
      "points": 16,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4
    },
    {
      "num": 18,
      "name": "SGT ALLEN",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 5,
      "sl": true,
      "asl": false,
      "weapon": "M1 .3 Calibre Carbine",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 3,
      "fp_range_5": 4,
      "morale": 5,
      "points": 55,
      "kia_unpinned": 8,
      "panic": 7,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": 7,
      "notes": "Reduced Hand Capacity."
    },
     {
      "num": 19,
      "name": "PFC MACGOWAN",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "BAR M1918A2",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 3,
      "fp_range_3": 4,
      "fp_range_4": 4,
      "fp_range_5": 5,
      "morale": 3,
      "points": 38,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 5
    },
    {
      "num": 20,
      "name": "CPL HULL",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": true,
      "weapon": "M1 Garand",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 4,
      "points": 42,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 6,
      "notes": "Reduced Hand Capacity if SL."
    },
    {
      "num": 21,
      "name": "PVT MALY",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "M1 Thompson",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "morale": 3,
      "points": 14,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4
    },
    {
      "num": 22,
      "name": "PVT CANTATORE",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "M1 Thompson",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "morale": 2,
      "points": 9,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 3
    },
    {
      "num": 23,
      "name": "PVT COATES",
      "card_type": "Man",
      "ccv_unpinned_armed": null, // Not explicitly shown on sketch card
      "ccv_unpinned_unarmed": null, // Not explicitly shown on sketch card
      "sl": false,
      "asl": false,
      "weapon": "M1 Thompson", // Inferred from sketch image style
      "breakdown": 6, // Inferred as standard
      "fp_range_0": 0, // Inferred as standard for Thompson
      "fp_range_1": 0, // Inferred
      "fp_range_2": 0, // Inferred
      "fp_range_3": 1, // Inferred
      "fp_range_4": 3, // Inferred
      "fp_range_5": 5, // Inferred
      "morale": null, // Not shown on sketch card
      "points": null, // Not shown on sketch card
      "kia_unpinned": null, // Not explicitly shown (sketch KIA is likely pinned)
      "panic": 5,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "Sketch card only. Missing some stats (Morale, PT, Unpinned CCV/KIA)."
    },
    {
      "num": 24,
      "name": "PVT CRAIN",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "M1 Thompson",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "morale": 1,
      "points": 5,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": 3
    },
    {
      "num": 25,
      "name": "PVT COGGINS",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "M1 Thompson",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "morale": 4,
      "points": 19,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5
    },
    {
      "num": 26,
      "name": "PVT DEGI",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "M1 Thompson",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "morale": 2,
      "points": 9,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 3
    },
    {
      "num": 27,
      "name": "PVT MARTIN",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "M1 Thompson",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "morale": 4, // Value from Weapon card
      "points": 11, // Value from Weapon card
      "kia_unpinned": 8,
      "panic": 4, // Value from Sketch card
      "ccv_pinned_armed": 1, // Value from Sketch card
      "ccv_pinned_unarmed": -2, // Value from Sketch card
      "kia_pinned": 9, // Value from Sketch card
      "rout": 4, // Value from Sketch card
      "notes": "Morale and PT from Weapon card conflict with Sketch card (Morale 2, PT 4)."
    },
    {
      "num": 28,
      "name": "CPL SHELLEY",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": true,
      "weapon": "M2 60mm Mortar",
      "breakdown": 6,
      "fp_range_0": 0, // Mortars use To Hit, not FP ranges directly
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
       "weapon_details": {
           "type": "Mortar",
           "range_0_th": "0 [2]",
           "range_1_th": "0-1 [1]",
           "range_2_th": "0-2 [0]",
           "range_3_th": "0-3 [0-1]",
           "range_4_th": "NA/1FP",
           "range_5_th": "NA/2FP",
           "no_moving_fire": true,
           "ammo": 3
       },
      "morale": 3,
      "points": 61,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "No Secondary Weapons Allowed. No Moving Fire. Breakdown notation: [X4-6] X5-6."
    },
    {
      "num": 29,
      "name": "37mm M3A1",
      "card_type": "Support Weapon",
      "ccv_unpinned_armed": 4, // CCV listed on weapon card
      "ccv_unpinned_unarmed": 4, // CCV listed on weapon card
      "sl": false,
      "asl": false,
      "weapon": "37mm M3A1",
      "breakdown": 6,
      "fp_range_0": 0, // Guns use To Hit, not FP ranges directly
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
       "weapon_details": {
           "type": "Gun",
           "range_0_th": "0",
           "range_1_th": "0-1",
           "range_2_th": "0-2",
           "range_3_th": "0-3",
           "range_4_th": "0-4",
           "range_5_th": "0-5"
       },
      "morale": 4, // Value from Weapon card
      "points": 185,
      "kia_unpinned": 9, // Value from both cards
      "panic": 4,
      "ccv_pinned_armed": 0, // CCV listed on sketch card
      "ccv_pinned_unarmed": 0, // CCV listed on sketch card
      "kia_pinned": 9, // Value from both cards
      "rout": 6,
      "notes": "Pinned: requires Rally 3. Rout: 0r RNC > 6. No Moving Fire. Breakdown notation: X5-6."
    },
    {
      "num": 30,
      "name": "57mm M1",
      "card_type": "Support Weapon",
      "ccv_unpinned_armed": 4, // CCV listed on weapon card
      "ccv_unpinned_unarmed": 4, // CCV listed on weapon card
      "sl": false,
      "asl": false,
      "weapon": "57mm M1",
      "breakdown": 6,
      "fp_range_0": 0, // Guns use To Hit, not FP ranges directly
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
       "weapon_details": {
           "type": "Gun",
           "range_0_th": "0",
           "range_1_th": "0-1",
           "range_2_th": "0-2",
           "range_3_th": "0-3",
           "range_4_th": "0-4",
           "range_5_th": "0-5"
       },
      "morale": 4, // Value from Weapon card
      "points": 185,
      "kia_unpinned": 9, // Value from both cards
      "panic": 6,
      "ccv_pinned_armed": 0, // CCV listed on sketch card
      "ccv_pinned_unarmed": 0, // CCV listed on sketch card
      "kia_pinned": 9, // Value from both cards
      "rout": 6,
      "notes": "Pinned: requires Rally 3. Rout: 0r RNC > 6. No Moving Fire. Breakdown notation: X5-6."
    },
    {
      "num": 31,
      "name": "M3 HALFTRACK",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null, // CCV not applicable for vehicles in this format
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "M2 HMG + M1919 MMGs", // Placeholder based on FP values and card art
      "breakdown": 6,
      "fp_range_0": 7,
      "fp_range_1": 8,
      "fp_range_2": 9,
      "fp_range_3": 10,
      "fp_range_4": 11,
      "fp_range_5": 12,
      "to_hit_range_0": null, // Does not use To Hit chart
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "morale": 4,
      "points": 141,
      "kia_unpinned": null, // KIA not applicable for vehicles in this format
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 3,
      "ovr": 3,
      "ce": 9,
      "bog": "4/w7",
      "mg": "X6",
      "armor": "i:s-1/k0",
      "flank": "i-2/s-1/k0",
      "pinned_rule": "requires Rally 3", // From sketch card
      "available": null, // Not listed on weapon card
      "notes": "Breakdown notation: X5-6."
    },
    {
      "num": 32,
      "name": "M8 GREYHOUND",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "Main Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 5,
      "fp_range_1": 6,
      "fp_range_2": 7,
      "fp_range_3": 8,
      "fp_range_4": 9,
      "fp_range_5": 10,
      "to_hit_range_0": null, // Does not use To Hit chart
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "morale": 4,
      "points": 192,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 1,
      "ovr": 2,
      "ce": 9,
      "bog": "4/w7",
      "mg": "X6",
      "armor": "i:s1/k2",
      "flank": "i:s0/k1",
      "pinned_rule": "requires Rally 3", // From sketch card
      "available": "1943-1945", // From sketch card
      "notes": "Breakdown notation: X5-6."
    },
    {
      "num": 33,
      "name": "M3A1 STUART (Early)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "Main Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 7,
      "fp_range_1": 8,
      "fp_range_2": 9,
      "fp_range_3": 10,
      "fp_range_4": 11,
      "fp_range_5": 12,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "morale": 4,
      "points": 308,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 1,
      "ovr": 3,
      "ce": 9,
      "bog": "0/0",
      "mg": "X6",
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "pinned_rule": "requires Rally 3", // From sketch card
      "available": "September 1942", // From sketch card
      "notes": "Breakdown notation: X5-6."
    },
     {
      "num": 33,
      "name": "M3A1 STUART (Button Up)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "Main Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 3,
      "fp_range_1": 4,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 5,
      "fp_range_5": 6,
      "to_hit_range_0": "1", // To Hit listed on weapon card
      "to_hit_range_1": "0",
      "to_hit_range_2": "0-1",
      "to_hit_range_3": "0-2",
      "to_hit_range_4": "0-3",
      "to_hit_range_5": "0-3",
      "morale": 4,
      "points": 185,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 1,
      "ovr": 1,
      "ce": 9,
      "bog": "9/9",
      "mg": "X6",
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "pinned_rule": null, // Not listed on this card
      "available": null, // Not listed on this card
      "notes": "Button Up. Breakdown notation: X5-6."
    },
    {
      "num": 34,
      "name": "M4(75) SHERMAN",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "75mm Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 10,
      "fp_range_1": 11,
      "fp_range_2": 12,
      "fp_range_3": 13,
      "fp_range_4": 14,
      "fp_range_5": 15,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "morale": 4,
      "points": 418,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 4,
      "ovr": 4,
      "ce": 9,
      "bog": "6/w0",
      "mg": "X6",
      "armor": "i4/s5/k6",
      "flank": "i2/s3/k4",
      "pinned_rule": null, // Not listed on this card
      "available": null, // Not listed on this card
      "notes": "Breakdown notation: X5-6."
    },
     {
      "num": 34,
      "name": "M4(75) SHERMAN (Button Up)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "75mm Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 3,
      "fp_range_1": 4,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 5,
      "fp_range_5": 6,
      "to_hit_range_0": "1",
      "to_hit_range_1": "0",
      "to_hit_range_2": "0-1",
      "to_hit_range_3": "0-2",
      "to_hit_range_4": "0-3",
      "to_hit_range_5": "0-3",
      "morale": 4,
      "points": 185,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 4,
      "ovr": 2,
      "ce": 9,
      "bog": "5/w9",
      "mg": "X6",
      "armor": "i4/s5/k6",
      "flank": "i2/s3/k4",
      "pinned_rule": null, // Not listed on this card
      "available": "1943",
      "notes": "Button Up. Breakdown notation: X5-6."
    },
    {
      "num": 35,
      "name": "M10 WOLVERINE (Sketch)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": null, // No weapon stats on this card
      "breakdown": null,
      "fp_range_0": null,
      "fp_range_1": null,
      "fp_range_2": null,
      "fp_range_3": null,
      "fp_range_4": null,
      "fp_range_5": null,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "morale": null,
      "points": null,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": null,
      "ovr": null,
      "ce": null,
      "bog": null,
      "mg": null,
      "armor": "i4/s5/k6",
      "flank": "i1/s2/k3",
      "pinned_rule": "requires Rally 3",
      "available": "March 1943",
      "notes": "Sketch card only - No combat stats."
    },
     {
      "num": 35,
      "name": "M10 WOLVERINE (OVR 3)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "76mm Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 6,
      "fp_range_1": 7,
      "fp_range_2": 8,
      "fp_range_3": 9,
      "fp_range_4": 10,
      "fp_range_5": 11,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "morale": 4,
      "points": 327,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 4,
      "ovr": 3,
      "ce": 9,
      "bog": "6/w0",
      "mg": "X6",
      "armor": "i4/s5/k6", // Matches sketch
      "flank": "i1/s2/k3", // Matches sketch
      "pinned_rule": null, // Not listed on this card (but on sketch)
      "available": null, // Not listed on this card (but on sketch)
      "notes": "Breakdown notation: X5-6."
    },
    {
      "num": 36,
      "name": "M4A3(76) SHERMAN (Button Up)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "76mm Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 3,
      "fp_range_1": 4,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 5,
      "fp_range_5": 6,
      "to_hit_range_0": "1",
      "to_hit_range_1": "0",
      "to_hit_range_2": "0-1",
      "to_hit_range_3": "0-2",
      "to_hit_range_4": "0-3",
      "to_hit_range_5": "0-3",
      "morale": 4,
      "points": 458,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 4,
      "ovr": 2,
      "ce": 9,
      "bog": "8/w0",
      "mg": "X6",
      "armor": "i5/s6/k7",
      "flank": "i2/s3/k4",
      "pinned_rule": null, // Not listed on this card
      "available": "July 1944",
      "notes": "Button Up. Breakdown notation: X5-6."
    },
     {
      "num": 36,
      "name": "M4A3(76) SHERMAN",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "76mm Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 10,
      "fp_range_1": 11,
      "fp_range_2": 12,
      "fp_range_3": 13,
      "fp_range_4": 14,
      "fp_range_5": 15,
      "to_hit_range_0": "1",
      "to_hit_range_1": "0",
      "to_hit_range_2": "0-1",
      "to_hit_range_3": "0-2",
      "to_hit_range_4": "0-3",
      "to_hit_range_5": "0-3",
      "morale": 4,
      "points": 458,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 4,
      "ovr": 4,
      "ce": 9,
      "bog": "9/w0",
      "mg": "X6",
      "armor": "i5/s6/k7",
      "flank": "i2/s3/k4",
      "pinned_rule": null, // Not listed on this card
      "available": null, // Not listed on this card
      "notes": "Breakdown notation: X5-6."
    },
    {
      "num": 37,
      "name": "M26 PERSHING",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "90mm Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 10,
      "fp_range_1": 11,
      "fp_range_2": 12,
      "fp_range_3": 13,
      "fp_range_4": 14,
      "fp_range_5": 15,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "morale": 4,
      "points": 535,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 5,
      "ovr": 5,
      "ce": 9,
      "bog": "8/w9",
      "mg": "X6",
      "armor": "i7/s8/k9",
      "flank": "i4/s5/k6",
      "pinned_rule": null, // Only Button Up is on sketch
      "available": "March 1945", // From sketch card
      "notes": "Button Up. Breakdown notation: X5-6." // Button Up from sketch card
    },
     {
      "num": 37,
      "name": "M26 PERSHING (Button Up Sketch)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "90mm Gun + MG", // Assumed
      "breakdown": null, // Not on sketch
      "fp_range_0": null, // Not on sketch
      "fp_range_1": null,
      "fp_range_2": null,
      "fp_range_3": null,
      "fp_range_4": null,
      "fp_range_5": null,
      "to_hit_range_0": null, // Not on sketch
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "morale": null, // Not on sketch
      "points": null, // Not on sketch
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": null, // Not on sketch
      "ovr": 2, // From sketch
      "ce": null, // Not on sketch
      "bog": null, // Not on sketch
      "mg": null, // Not on sketch
      "armor": "i7/s8/k9", // From sketch
      "flank": "i4/s5/k6", // From sketch
      "pinned_rule": null, // Button Up rule is present instead
      "available": "March 1945", // From sketch
      "notes": "Button Up (from sketch). Sketch card only - Missing combat stats (FP/To Hit, Morale, PT, Effect Number, CE, BOG, MG)."
    },
    {
      "num": 38,
      "name": "M24 CHAFFEE",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "75mm Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 10,
      "fp_range_1": 11,
      "fp_range_2": 12,
      "fp_range_3": 13,
      "fp_range_4": 14,
      "fp_range_5": 15,
      "to_hit_range_0": "1",
      "to_hit_range_1": "0",
      "to_hit_range_2": "0-1",
      "to_hit_range_3": "0-2",
      "to_hit_range_4": "0-3",
      "to_hit_range_5": "0-3",
      "morale": 4,
      "points": 422,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 4,
      "ovr": 4,
      "ce": 9,
      "bog": "9/w9",
      "mg": "X6",
      "armor": "i3/s4/k5",
      "flank": "i1/s2/k3",
      "pinned_rule": null, // Not listed on this card (but on Button Up variant)
      "available": "November 1944", // Listed on Button Up variant, assume applies here
      "notes": "Breakdown notation: X5-6."
    },
     {
      "num": 38,
      "name": "M24 CHAFFEE (Button Up)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "75mm Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 3,
      "fp_range_1": 4,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 5,
      "fp_range_5": 6,
      "to_hit_range_0": "1",
      "to_hit_range_1": "0",
      "to_hit_range_2": "0-1",
      "to_hit_range_3": "0-2",
      "to_hit_range_4": "0-3",
      "to_hit_range_5": "0-3",
      "morale": 4,
      "points": 422,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 4,
      "ovr": 4,
      "ce": 9,
      "bog": "0/w0", // Value from card
      "mg": "X6",
      "armor": "i3/s4/k5",
      "flank": "i1/s2/k3",
      "pinned_rule": null, // Not listed on this card
      "available": "November 1944",
      "notes": "Button Up. Breakdown notation: X5-6."
    },
    {
      "num": 39,
      "name": "M8 HMC",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "75mm Howitzer + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 6,
      "fp_range_1": 7,
      "fp_range_2": 8,
      "fp_range_3": 9,
      "fp_range_4": 10,
      "fp_range_5": 11,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "morale": 4,
      "points": 296,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 4,
      "ovr": 3,
      "ce": 9,
      "bog": "7/w0",
      "mg": "X6",
      "armor": "i3/s4/k5",
      "flank": "i1/s2/k3",
      "pinned_rule": "requires Rally 3", // From sketch card
      "available": "1943-1945", // From sketch card
      "notes": "Breakdown notation: X5-6."
    },
     {
      "num": 40,
      "name": "M20 UTILITY CAR (Sketch)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": null, // No weapon stats on this card
      "breakdown": null,
      "fp_range_0": null,
      "fp_range_1": null,
      "fp_range_2": null,
      "fp_range_3": null,
      "fp_range_4": null,
      "fp_range_5": null,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "morale": null,
      "points": null,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": null,
      "ovr": null,
      "ce": null,
      "bog": null,
      "mg": null,
      "armor": "i0/s1/k2",
      "flank": "i-1/s0/k1",
      "pinned_rule": "requires Rally 3",
      "available": "1944-1945",
      "notes": "Sketch card only - No combat stats."
    },
     {
      "num": 40,
      "name": "M20 UTILITY CAR (HMG)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": ".50 cal HMG", // Placeholder based on art and FP values
      "breakdown": 6,
      "fp_range_0": 12,
      "fp_range_1": 13,
      "fp_range_2": 14,
      "fp_range_3": 15,
      "fp_range_4": 16,
      "fp_range_5": 17,
      "to_hit_range_0": null, // Does not use To Hit chart
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "morale": 3,
      "points": 205,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 4,
      "ovr": 4,
      "ce": 9,
      "bog": "4/w7",
      "mg": "X6",
      "armor": "i0/s1/k2",
      "flank": "i-1/s0/k1",
      "pinned_rule": null, // Not listed on this card (but on sketch)
      "available": null, // Not listed on this card (but on sketch)
      "notes": "Breakdown notation: X6."
    },
    {
      "num": 41,
      "name": "M5A1 STUART (Sketch)",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": null, // No weapon stats on this card
      "breakdown": null,
      "fp_range_0": null,
      "fp_range_1": null,
      "fp_range_2": null,
      "fp_range_3": null,
      "fp_range_4": null,
      "fp_range_5": null,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "morale": null,
      "points": null,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": null,
      "ovr": null,
      "ce": null,
      "bog": null,
      "mg": null,
      "armor": "i3/s4/k5",
      "flank": "i1/s2/k3",
      "pinned_rule": "requires Rally 3",
      "available": "November 1942",
      "notes": "Sketch card only - No combat stats."
    },
     {
      "num": 41,
      "name": "M5A1 STUART",
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "weapon": "Main Gun + MG", // Placeholder
      "breakdown": 6,
      "fp_range_0": 7,
      "fp_range_1": 8,
      "fp_range_2": 9,
      "fp_range_3": 10,
      "fp_range_4": 11,
      "fp_range_5": 12,
      "to_hit_range_0": "1",
      "to_hit_range_1": "0",
      "to_hit_range_2": "0-1",
      "to_hit_range_3": "0-2",
      "to_hit_range_4": "0-3",
      "to_hit_range_5": "0-3",
      "morale": 4,
      "points": 313,
      "kia_unpinned": null,
      "panic": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "rout": null,
      "effect_number": 1,
      "ovr": 3,
      "ce": 9,
      "bog": "7/w9",
      "mg": "X6",
      "armor": "i3/s4/k5", // Matches sketch
      "flank": "i1/s2/k3", // Matches sketch
      "pinned_rule": null, // Not listed on this card (but on sketch)
      "available": null, // Not listed on this card (but on sketch)
      "notes": "Breakdown notation: X5-6."
    },
    {
      "num": 42,
      "name": "SGT TAYLOR",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": true,
      "asl": false, // ASL false because SGT rank indicates SL primarily
      "weapon": "Model 1903 Springfield",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 5,
      "points": 47,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": 6,
      "notes": "Reduced Hand Capacity."
    },
    {
      "num": 43,
      "name": "CPL HANEY",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false, // SL false because CPL rank indicates ASL primarily
      "asl": true,
      "weapon": "Model 1903 Springfield",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 4,
      "points": 38,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "Reduced Hand Capacity if SL."
    },
    {
      "num": 44,
      "name": "PFC HANKINS",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "BAR M1918A2",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 3,
      "fp_range_3": 4,
      "fp_range_4": 4,
      "fp_range_5": 5,
      "morale": 2,
      "points": 44,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 3,
      "notes": null
    }
  ]
};