window.britainData = {
  "name": "Britain",
  "hand_capacity": 6,
  "discard": 1,
  "discard_condition_no_action": true,
  "notes": "May discard up to 2 cards on Player.",
  "broken_squad": 50,
  "nationalTactics": {
    "priorityModifiers": {
      "FIRE_DEF": 1.2,             // Defensive fire doctrine
      "ENTRENCH": 1.2,             // Prepared positions
      "RALLY_ALL": 1.1,            // Stiff upper lip
      "MOVE_CAUTIOUS": 1.2,        // Methodical advance
      "PLACE_TERRAIN_SELF": 1.1,   // Terrain usage
      "LAY_SMOKE": 1.1             // Tactical smoke
    },
    "description": "British tactics emphasize defensive positions, methodical advances, and maintaining morale."
  },
  "units": [
    {
      "num": 1,
      "name": "SGT VASEY",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 5,
      "sl": true,
      "asl": false,
      "weapon": "Sten Mk II",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
          "type": "Machine Pistol"
      },
      "morale": 5,
      "points": 51,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": 6,
      "notes": "Reduced Hand Capacity."
    },
    {
      "num": 2,
      "name": "CPL BARNARD",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": true,
      "weapon": "Lee Enfield Mk I",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 4,
      "points": 40,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "Reduced Hand Capacity if SL."
    },
    {
      "num": 3,
      "name": "PFC SCARBOROUGH",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Bren",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 6,
      "fp_range_5": 6,
      "weapon_details": {
          "type": "Light Machinegun"
      },
      "morale": 4,
      "points": 61,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "No Secondary Weapons Allowed."
    },
    {
      "num": 4,
      "name": "PVT TRESHAM",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Lee Enfield Mk I",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 15,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4,
      "notes": ""
    },
    {
      "num": 5,
      "name": "PVT HODGE",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Lee Enfield Mk I",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 4,
      "points": 20,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5,
      "notes": ""
    },
    {
      "num": 6,
      "name": "PVT WILLIS",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Lee Enfield Mk I",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 15,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4,
      "notes": ""
    },
    {
      "num": 7,
      "name": "PVT CLEARY",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "Lee Enfield Mk I",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 1,
      "points": 5,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": 2,
      "notes": ""
    },
    {
      "num": 8,
      "name": "PVT COTTRELL",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Lee Enfield Mk I",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 15,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4,
      "notes": ""
    },
    {
      "num": 9,
      "name": "PVT BELL",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Lee Enfield Mk I",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 3,
      "notes": ""
    },
    {
      "num": 10,
      "name": "PVT MOON",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Lee Enfield Mk I",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 3,
      "notes": ""
    },
    {
      "num": 11,
      "name": "PFC DAVIS",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "PIAT",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
      "weapon_details": {
           "type": "PIAT",
           "ammo": "2 [2]",
           "range_3_th": "0-1",
           "range_4_th": "0-2",
           "range_5_th": "0-3",
           "no_moving_fire": true,
           "effect_number": 2,
           "alternate_effect_number": 2
       },
      "morale": 4,
      "points": 85,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "AVAILABLE: 4/1943. No Secondary Weapons Allowed. No Moving Fire. Breakdown: X3-6."
    },
     {
      "num": 12,
      "name": "PFC GILFALIN",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Bren",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 6,
      "fp_range_5": 6,
       "weapon_details": {
          "type": "Light Machinegun"
      },
      "morale": 3,
      "points": 46,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4,
      "notes": "No Secondary Weapons Allowed."
    },
     {
      "num": 13,
      "name": "PFC PALMER",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Vickers Mk I",
      "breakdown": 6,
      "fp_range_0": 7,
      "fp_range_1": 8,
      "fp_range_2": 9,
      "fp_range_3": 10,
      "fp_range_4": 11,
      "fp_range_5": 12,
      "weapon_details": {
           "type": "MMG",
           "sustained_fp_0": 3,
           "sustained_fp_1": 4,
           "sustained_fp_2": 4,
           "sustained_fp_3": 5,
           "sustained_fp_4": 5,
           "sustained_fp_5": 6,
           "no_moving_fire": true
       },
      "morale": 4,
      "points": 114,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "No Moving Fire. No Secondary Weapons Allowed. Breakdown: [X5-6] X6."
    },
     {
      "num": 14,
      "name": "PVT VANE",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Portable No.5 Mk I",
      "breakdown": 6,
      "fp_range_0": null,
      "fp_range_1": null,
      "fp_range_2": null,
      "fp_range_3": null,
      "fp_range_4": null,
      "fp_range_5": 12,
      "weapon_details": {
           "type": "Flamethrower",
           "range": 5,
           "fp": 12,
           "no_def_tem": true,
           "no_ff_inf_bonus": true,
           "moving_fire_not_halved": true
       },
      "morale": 4,
      "points": 72,
      "kia_unpinned": 7,
      "panic": 5,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 8,
      "rout": 5,
      "notes": "* No Def TEM, No FF/INF Bonus. * Moving Fire Not Halved. No Secondary Weapons Allowed. Breakdown: X5-6."
    },
    {
      "num": 15,
      "name": "PFC SHAW",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Sten Mk II",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
          "type": "Machine Pistol"
      },
      "morale": 4,
      "points": 21,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5,
      "notes": ""
    },
     {
      "num": 16,
      "name": "PVT ROSS",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Sten Mk II",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
          "type": "Machine Pistol"
      },
      "morale": 3,
      "points": 16,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4,
      "notes": ""
    },
     {
      "num": 17,
      "name": "PVT SHANNON",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "Sten Mk II",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
       "weapon_details": {
          "type": "Machine Pistol"
      },
      "morale": 5,
      "points": 26,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": 6,
      "notes": ""
    },
    {
      "num": 18,
      "name": "PVT WHALEY",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Sten Mk II",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
       "weapon_details": {
          "type": "Machine Pistol"
      },
      "morale": 2,
      "points": 11,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 3,
      "notes": ""
    },
    {
      "num": 19,
      "name": "PVT COLE",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "Sten Mk II",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
       "weapon_details": {
          "type": "Machine Pistol"
      },
      "morale": 1,
      "points": 5,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": 2,
      "notes": ""
    },
    {
      "num": 20,
      "name": "PVT COLEMAN",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "PIAT",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
      "weapon_details": {
           "type": "PIAT",
           "ammo": "2 [2]",
           "range_3_th": "0-1",
           "range_4_th": "0-2",
           "range_5_th": "0-3",
           "no_moving_fire": true,
           "effect_number": 2,
           "alternate_effect_number": 2
       },
      "morale": 3,
      "points": 64,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4,
      "notes": "AVAILABLE: 4/1943. No Secondary Weapons Allowed. No Moving Fire. Breakdown: X3-6."
    },
    {
      "num": 21,
      "name": "SGT O'NEIL",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 4,
      "sl": true,
      "asl": false,
      "weapon": "Sten Mk II",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
          "type": "Machine Pistol"
      },
      "morale": 4,
      "points": 46,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "Reduced Hand Capacity."
    },
    {
      "num": 22,
      "name": "CPL BURNS",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": true,
      "weapon": "Sten Mk II",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
          "type": "Machine Pistol"
      },
      "morale": 3,
      "points": 36,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4,
      "notes": "Reduced Hand Capacity if SL."
    },
    {
      "num": 23,
      "name": "PFC WATNEY",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "2 inch Mortar",
      "breakdown": 6,
      "morale": 3,
      "points": 54,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4,
      "weapon_details": {
        "type": "Mortar",
        "effect_number": 2,
        "to_hit_ranges": ["1 [3]", "0 [2]", "0-1 [1]", "0-2 [0]", "0-3 [0-1]", null],
        "fp_ranges": [null, null, null, null, null, "2FP"],
        "no_moving_fire": true
      },
      "notes": "No Secondary Weapons Allowed. Breakdown: [X4-6] X5-6."
    },
    {
      "num": 24,
      "name": "PVT WHITESELL",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "Lee Enfield Mk I",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 5,
      "points": 25,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": 6,
      "notes": ""
    },
    {
      "num": 25,
      "name": "PVT McNAMARA",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Lee Enfield Mk I",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 3,
      "notes": ""
    },
    {
      "num": 26,
      "name": "PFC OLDAKER",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Boys",
      "breakdown": 6,
      "fp_range_0": 1,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 1,
      "fp_range_4": 1,
      "fp_range_5": 1,
      "weapon_details": {
           "type": "Anti-Tank Rifle",
           "effect_number": 0,
           "to_hit_range_0": 6,
           "to_hit_range_1": 5,
           "to_hit_range_2": 5,
           "to_hit_range_3": 4,
           "to_hit_range_4": 4,
           "to_hit_range_5": 3,
           "flank_bonus": -1,
           "no_moving_fire": true
       },
      "morale": 3,
      "points": 14,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4,
      "notes": "No Secondary Weapons Allowed. No Moving Fire."
    },
     {
      "num": 27,
      "name": "Q.F. 2pdr/L52",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 190,
      "kia_unpinned": 9,
      "panic": 6,
      "panic_pinned": 4,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": 6,
      "weapon_details": {
        "type": "AT Gun",
        "effect_number": 0,
        "alternate_effect_number": 2,
        "breakdown": 6,
        "to_hit_ranges": ["0", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. No Moving Fire."
    },
    {
      "num": 28,
      "name": "Q.F. 6pdr/L45",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 216,
      "kia_unpinned": 9,
      "panic": 6,
      "panic_pinned": 4,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": 6,
      "weapon_details": {
        "type": "AT Gun",
        "effect_number": 0,
        "alternate_effect_number": 3,
        "breakdown": 6,
        "to_hit_ranges": ["0", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. No Moving Fire."
    },
     {
      "num": 31,
      "name": "Mk VIA (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "9/w9",
      "morale": 5,
      "points": 207,
      "armor": "i:s0/k1",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "ranged_firepower_combined": [
          { "to_hit": null, "fp": 4 },
          { "to_hit": null, "fp": 5 },
          { "to_hit": null, "fp": 6 },
          { "to_hit": null, "fp": 6 },
          { "to_hit": null, "fp": 7 },
          { "to_hit": null, "fp": 7 }
        ]
      },
      "available": "1936-1942",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 31,
      "name": "Mk VIA (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "0/w0",
      "morale": 5,
      "points": 207,
      "armor": "i:s0/k1",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "ranged_firepower_combined": [
          { "to_hit": null, "fp": 5 },
          { "to_hit": null, "fp": 6 },
          { "to_hit": null, "fp": 7 },
          { "to_hit": null, "fp": 8 },
          { "to_hit": null, "fp": 9 },
          { "to_hit": null, "fp": 10 }
        ]
      },
      "available": "1936-1942",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 32,
      "name": "T17E1 STAGHOUND I (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "3/w6",
      "morale": 5,
      "points": 302,
      "armor": "i1/s2/k3",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "ranged_firepower_combined": [
          { "to_hit": "2", "fp": 2 },
          { "to_hit": "1", "fp": 3 },
          { "to_hit": "0", "fp": 3 },
          { "to_hit": "0-1", "fp": 4 },
          { "to_hit": "0-2", "fp": 4 },
          { "to_hit": "0-3", "fp": 5 }
        ]
      },
      "available": "1943-1945",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 32,
      "name": "T17E1 STAGHOUND I (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "4/w7",
      "morale": 5,
      "points": 302,
      "armor": "i1/s2/k3",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 5 },
          { "to_hit": "0-1", "fp": 6 },
          { "to_hit": "0-2", "fp": 7 },
          { "to_hit": "0-3", "fp": 8 },
          { "to_hit": "0-4", "fp": 9 },
          { "to_hit": "0-5", "fp": 10 }
        ]
      },
      "available": "1943-1945",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
    {
      "num": 33,
      "name": "WASP (OVR 5)",
      "card_type": "Vehicle",
      "ovr": 5,
      "ce": 9,
      "button_up": false,
      "bog": "0/w0",
      "morale": 5,
      "points": 152,
      "armor": "i:s0/k1",
      "flank": "i-2/s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "flamethrower_details": {
        "type": "Flamethrower",
        "range": 4,
        "fp": 14,
        "no_def_tem": true,
        "no_ff_inf_bonus": true,
        "moving_fire_not_halved": true
      },
      "mg_fp_ranges": [2, 3, 4, 5, 6, 6],
      "available": "1944-1945",
      "notes": "* No Defensive TEM, No FF Bonus. * Moving Fire not Halved. Pinned requires Rally 3."
    },
    {
      "num": 33,
      "name": "WASP",
      "card_type": "Vehicle",
      "ovr": null,
      "ce": null,
      "button_up": null,
      "bog": "0/w0",
      "morale": 6,
      "points": null,
      "armor": "i:s0/k1",
      "flank": "i-2/s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
       "flamethrower_details": {
        "type": "Flamethrower",
        "range": 4,
        "fp": 14,
        "no_def_tem": true,
        "no_ff_inf_bonus": true,
        "moving_fire_not_halved": true
      },
      "available": "1944-1945",
      "notes": "* No Defensive TEM, No FF Bonus. * Moving Fire not Halved. Pinned requires Rally 3. Rout: 0r RNC > 6."
    },
    {
      "num": 34,
      "name": "BREN CARRIER I (OVR 1)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": 9,
      "button_up": false,
      "bog": "0/w0",
      "morale": 5,
      "points": 94,
      "armor": "i:s0/k1",
      "flank": "i-2/s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 0,
        "to_hit_ranges": ["6", "5", "5", "4", "4", "3"],
        "fp_ranges": [2, 3, 4, 5, 6, 6],
        "no_moving_fire": true
      },
      "available": "1939-1945",
      "notes": "* No Moving Fire Allowed. +1 To Hit vs Moving Target. +2 To Hit if Bogged / Immobilized. Pinned requires Rally 3. Rout: 0r RNC > 6."
    },
    {
      "num": 35,
      "name": "A15CS CRUSADER I (Button Up)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": null,
      "button_up": true,
      "bog": "5/w9",
      "morale": 5,
      "points": 438,
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "alternate_effect_number": 1,
        "ranged_firepower_combined": [
          { "to_hit": "2", "fp": 3 },
          { "to_hit": "1", "fp": 4 },
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 5 },
          { "to_hit": "0-3", "fp": 6 }
        ]
      },
      "available": "1941-1943",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 35,
      "name": "A15CS CRUSADER I (OVR 4)",
      "card_type": "Vehicle",
      "ovr": 4,
      "ce": 9,
      "button_up": false,
      "bog": "6/w0",
      "morale": 5,
      "points": 438,
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "alternate_effect_number": 1,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 7 },
          { "to_hit": "0-1", "fp": 8 },
          { "to_hit": "0-2", "fp": 9 },
          { "to_hit": "0-3", "fp": 10 },
          { "to_hit": "0-4", "fp": 11 },
          { "to_hit": "0-5", "fp": 12 }
        ]
      },
      "available": "1941-1943",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 36,
      "name": "A15 CRUSADER I (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "5/w9",
      "morale": 5,
      "points": 311,
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 0,
        "alternate_effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": "2", "fp": 3 },
          { "to_hit": "1", "fp": 4 },
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 5 },
          { "to_hit": "0-3", "fp": 6 }
        ]
      },
      "available": "1941-1943",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
    {
      "num": 36,
      "name": "A15 CRUSADER I (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "6/w0",
      "morale": 5,
      "points": 311,
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 0,
        "alternate_effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 6 },
          { "to_hit": "0-3", "fp": 7 },
          { "to_hit": "0-4", "fp": 8 },
          { "to_hit": "0-5", "fp": 9 }
        ]
      },
      "available": "1941-1943",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 37,
      "name": "A12 MATILDA II (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "4/w9",
      "morale": 5,
      "points": 356,
      "armor": "i4/s5/k6",
      "flank": "i4/s5/k6",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 0,
        "alternate_effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": "2", "fp": 1 },
          { "to_hit": "1", "fp": 2 },
          { "to_hit": "0", "fp": 2 },
          { "to_hit": "0-1", "fp": 3 },
          { "to_hit": "0-2", "fp": 3 },
          { "to_hit": "0-3", "fp": 4 }
        ]
      },
      "available": "1940-1943",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
    {
      "num": 37,
      "name": "A12 MATILDA II (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "5/w0",
      "morale": 5,
      "points": 356,
      "armor": "i4/s5/k6",
      "flank": "i4/s5/k6",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 0,
        "alternate_effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 5 },
          { "to_hit": "0-1", "fp": 6 },
          { "to_hit": "0-2", "fp": 7 },
          { "to_hit": "0-3", "fp": 8 },
          { "to_hit": "0-4", "fp": 9 },
          { "to_hit": "0-5", "fp": 10 }
        ]
      },
      "available": "1940-1943",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 38,
      "name": "SHERMAN VC FIREFLY (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "5/w9",
      "morale": 5,
      "points": 521,
      "armor": "i4/s5/k6",
      "flank": "i2/s3/k4",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "alternate_effect_number": 7,
        "ranged_firepower_combined": [
          { "to_hit": "2", "fp": 1 },
          { "to_hit": "1", "fp": 2 },
          { "to_hit": "0", "fp": 2 },
          { "to_hit": "0-1", "fp": 3 },
          { "to_hit": "0-2", "fp": 3 },
          { "to_hit": "0-3", "fp": 4 }
        ]
      },
      "available": "JUNE 1944",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
    {
      "num": 38,
      "name": "SHERMAN VC FIREFLY (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "6/w0",
      "morale": 5,
      "points": 521,
      "armor": "i4/s5/k6",
      "flank": "i2/s3/k4",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "alternate_effect_number": 7,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 2 },
          { "to_hit": "0-1", "fp": 3 },
          { "to_hit": "0-2", "fp": 4 },
          { "to_hit": "0-3", "fp": 5 },
          { "to_hit": "0-4", "fp": 6 },
          { "to_hit": "0-5", "fp": 7 }
        ]
      },
      "available": "JUNE 1944",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 39,
      "name": "A22 CHURCHILL VII (Button Up)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": null,
      "button_up": true,
      "bog": "3/w9",
      "morale": 5,
      "points": 531,
      "armor": "i6/s7/k8",
      "flank": "i5/s6/k7",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "ranged_firepower_combined": [
          { "to_hit": "2", "fp": 3 },
          { "to_hit": "1", "fp": 4 },
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 5 },
          { "to_hit": "0-3", "fp": 6 }
        ]
      },
      "available": "1944",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 39,
      "name": "A22 CHURCHILL VII (OVR 3)",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": 9,
      "button_up": false,
      "bog": "4/w0",
      "morale": 5,
      "points": 531,
      "armor": "i6/s7/k8",
      "flank": "i5/s6/k7",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 6 },
          { "to_hit": "0-3", "fp": 7 },
          { "to_hit": "0-4", "fp": 8 },
          { "to_hit": "0-5", "fp": 9 }
        ]
      },
      "available": "1944",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 40,
      "name": "A10 (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "6/w9",
      "morale": 5,
      "points": 305,
      "armor": "i1/s2/k3",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 0,
        "alternate_effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": "2", "fp": 3 },
          { "to_hit": "1", "fp": 4 },
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 5 },
          { "to_hit": "0-3", "fp": 6 }
        ]
      },
      "available": "1938-1941",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 40,
      "name": "A10 (OVR 3)",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": 9,
      "button_up": false,
      "bog": "7/w0",
      "morale": 5,
      "points": 305,
      "armor": "i1/s2/k3",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 0,
        "alternate_effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 7 },
          { "to_hit": "0-1", "fp": 8 },
          { "to_hit": "0-2", "fp": 9 },
          { "to_hit": "0-3", "fp": 10 },
          { "to_hit": "0-4", "fp": 11 },
          { "to_hit": "0-5", "fp": 12 }
        ]
      },
      "available": "1938-1941",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
    {
      "num": 41,
      "name": "A27M CROMWELL IV (Button Up)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": null,
      "button_up": true,
      "bog": "5/w9",
      "morale": 5,
      "points": 498,
      "armor": "i4/s5/k6",
      "flank": "i2/s3/k4",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "ranged_firepower_combined": [
          { "to_hit": "2", "fp": 3 },
          { "to_hit": "1", "fp": 4 },
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 5 },
          { "to_hit": "0-3", "fp": 6 }
        ]
      },
      "available": "1944-1945",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
    {
      "num": 41,
      "name": "A27M CROMWELL IV (OVR 3)",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": 9,
      "button_up": false,
      "bog": "6/w0",
      "morale": 5,
      "points": 498,
      "armor": "i4/s5/k6",
      "flank": "i2/s3/k4",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 6 },
          { "to_hit": "0-3", "fp": 7 },
          { "to_hit": "0-4", "fp": 8 },
          { "to_hit": "0-5", "fp": 9 }
        ]
      },
      "available": "1944-1945",
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
     {
      "num": 42,
      "name": "SEXTON",
      "card_type": "Vehicle",
      "ovr": null,
      "ce": null,
      "button_up": null,
      "bog": "6/w0",
      "morale": 5,
      "points": 329,
      "armor": "i0/s1/k2",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 5,
        "alternate_effect_number": 4,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 6 },
          { "to_hit": "0-3", "fp": 7 },
          { "to_hit": "0-4", "fp": 8 },
          { "to_hit": "0-5", "fp": 9 }
        ],
        "no_moving_fire": true
      },
      "available": "1943-1945",
      "notes": "Pinned requires Rally 3. +1 To Hit vs Moving target. +2 To Hit if Bogged / Immobilized. No Moving Fire Allowed."
    }
  ]
};