window.franceData = {
  "name": "France",
  "hand_capacity": 6,
  "discard": 1,
  "discard_condition_no_action": true,
  "notes": "May discard up to 1 card on Player.",
  "broken_squad": 50,
  "units": [
    {
      "num": 1,
      "name": "SGT VILLENEUVE",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": true,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 38,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity. ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 2,
      "name": "CPL DUBOIS",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": true,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 4,
      "points": 35,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity if SL. ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 3,
      "name": "PFC LARUE",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Chatellerault mle 24/29",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 6,
      "fp_range_5": 7,
      "weapon_details": {
        "type": "Light Machinegun"
      },
      "morale": 4,
      "points": 57,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 4,
      "name": "PVT CASSAVANT",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 4,
      "points": 15,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 5,
      "name": "PVT CORBEIL",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 1,
      "points": 4,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 6,
      "name": "PVT PICCARD",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 11,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 7,
      "name": "PVT LAFORTE",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 5,
      "points": 19,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 8,
      "name": "PVT DECAUTAUX",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 13,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 9,
      "name": "PVT BIENVENUE",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 4,
      "points": 15,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 10,
      "name": "PVT MEILEURE",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 8,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 11,
      "name": "PVT KASTLER",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 9,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 12,
      "name": "PVT ROUSSELLE",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 13,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 13,
      "name": "CPL HOULE",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "HotchKiss",
      "breakdown": 6,
      "fp_range_0": 6,
      "fp_range_1": 7,
      "fp_range_2": 8,
      "fp_range_3": 9,
      "fp_range_4": 10,
      "fp_range_5": 11,
      "weapon_details": {
           "type": "MMG",
           "sustained_fp_0": 3,
           "sustained_fp_1": 4,
           "sustained_fp_2": 4,
           "sustained_fp_3": 5,
           "sustained_fp_4": 5,
           "sustained_fp_5": 6,
           "no_moving_fire": true
       },
      "morale": 4,
      "points": 92,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. No Moving Fire. Breakdown: [X5-6] X6. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 14,
      "name": "PFC MONTCALM",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Portable Flamethrower",
      "breakdown": 6,
      "fp_range_0": null,
      "fp_range_1": null,
      "fp_range_2": null,
      "fp_range_3": null,
      "fp_range_4": null,
      "fp_range_5": 12,
      "weapon_details": {
           "type": "Flamethrower",
           "range": 5,
           "fp": 12,
           "no_def_tem": true,
           "no_ff_inf_bonus": true,
           "moving_fire_not_halved": true
       },
      "morale": 4,
      "points": 34,
      "kia_unpinned": 7,
      "panic": 5,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 8,
      "rout": null,
      "notes": "* No Def TEM, No FF/INF Bonus. * Moving Fire Not Halved. No Secondary Weapons Allowed. Breakdown: X5-6. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 15,
      "name": "PVT BRENTON",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 11,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 16,
      "name": "PVT BAUDET",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 11,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 17,
      "name": "PVT ROCHARD",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 5,
      "points": 19,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 18,
      "name": "PVT BOURASSA",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 8,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 19,
      "name": "PVT TARDIEU",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 1,
      "points": 4,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 20,
      "name": "PVT BERNET",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 5,
      "points": 22,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 21,
      "name": "SGT PETROU",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": true,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 4,
      "points": 43,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 22,
      "name": "CPL GOREUX",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": true,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 33,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity if SL. ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 23,
      "name": "PVT BARRAL",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 9,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 24,
      "name": "PVT LEBESQUE",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "MAS 36 CR39",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
       "weapon_details": {
          "type": "Bolt-Action Rifle"
      },
      "morale": 1,
      "points": 4,
      "kia_unpinned": 8,
      "panic": 1,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 25,
      "name": "PFC SARTE",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "morale": 3,
      "morale_pinned": 3,
      "points": 42,
      "kia_unpinned": 8,
      "panic": 3,
      "panic_pinned": 3,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "weapon_details": {
        "type": "Mortar",
        "name": "50mm Mle 37",
        "effect_number": 2,
        "breakdown": 6,
        "to_hit_ranges": ["1 [3]", "0 [2]", "0-1 [1]", "0-2 [0]", "0-3 [0-1]", null],
        "he_fp_ranges": ["2", "2", "2", "1", "1", null],
        "range_5_note": "Range 5: 2FP HE Area Fire",
        "no_moving_fire": true
      },
      "notes": "No Secondary Weapons Allowed. No Moving Fire. Breakdown: [X4-6] X5-6. ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 26,
      "name": "PFC LASALLE",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "morale": 4,
      "morale_pinned": 4,
      "points": 61,
      "kia_unpinned": 8,
      "panic": 4,
      "panic_pinned": 4,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "weapon_details": {
        "type": "Mortar",
        "name": "60mm Mle 35",
        "effect_number": 3,
        "breakdown": 6,
        "to_hit_ranges": ["0 [2]", "0-1 [1]", "0-2 [0]", "0-3 [0-1]", null, null],
        "fp_ranges": [null, null, null, null, "1FP", "2FP"],
        "he_fp_ranges": [null, null, null, null, null, null],
        "no_moving_fire": true
      },
      "notes": "No Secondary Weapons Allowed. No Moving Fire. Breakdown: [X4-6] X5-6. ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 27,
      "name": "PFC ROCHE",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Chatellerault mle 24/29",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 6,
      "fp_range_5": 7,
      "weapon_details": {
        "type": "Light Machinegun"
      },
      "morale": 3,
      "points": 43,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 28,
      "name": "37mm Mle 16 INF",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 191,
      "kia_unpinned": 9,
      "panic": 6,
      "panic_pinned": 4,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": null,
      "weapon_details": {
        "type": "AT Gun",
        "name": "37mm Mle 16 TRP",
        "effect_number": 1,
        "alternate_effect_number": 1,
        "breakdown": 6,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. No Moving Fire. ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 29,
      "name": "47mm SA Mle 37",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 225,
      "kia_unpinned": 9,
      "panic": 6,
      "panic_pinned": 4,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": null,
      "weapon_details": {
        "type": "AT Gun",
        "effect_number": 2,
        "alternate_effect_number": 2,
        "breakdown": 6,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. No Moving Fire. ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 30,
      "name": "75mm Mle 19",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 295,
      "kia_unpinned": 9,
      "panic": 6,
      "panic_pinned": 4,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": null,
      "weapon_details": {
        "type": "AT Gun",
        "effect_number": 4,
        "alternate_effect_number": 4,
        "breakdown": 6,
        "to_hit_ranges": ["0", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. No Moving Fire. ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 31,
      "name": "CHAR LEGER H39 (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "6/w9",
      "morale": 4,
      "points": 273,
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [2,3,3,4,4,5]
      },
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 31,
      "name": "CHAR LEGER H39 (CE)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "8/w0",
      "morale": 4,
      "points": 273,
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2,3,4,5,6,7]
      },
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 32,
      "name": "CHAR LEGER R35 (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "7/w9",
      "morale": 4,
      "points": 262,
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [2,3,3,4,4,5]
      },
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 32,
      "name": "CHAR LEGER R35 (CE)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "8/w0",
      "morale": 4,
      "points": 262,
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 0,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2,3,4,5,6,7]
      },
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 33,
      "name": "CHAR S-35 (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "5/w9",
      "morale": 4,
      "points": 297,
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 2,
        "alternate_effect_number": 2,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [2,3,3,4,4,5]
      },
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 33,
      "name": "CHAR S-35 (CE)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "6/w0",
      "morale": 4,
      "points": 297,
      "armor": "i2/s3/k4",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 2,
        "alternate_effect_number": 2,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2,3,4,5,6,7]
      },
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 34,
      "name": "CHAR B1-bis (Button Up)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": null,
      "button_up": true,
      "bog": "4/w9",
      "morale": 4,
      "points": 315,
      "armor": "i3/s4/k5",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun (75mm)",
        "effect_number": 4,
        "alternate_effect_number": 2,
        "second_alternate_effect_number": 2,
        "third_alternate_effect_number": 2,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [2,3,4,5,6,7]
      },
      "notes": "Pinned requires Rally 3 (Inferred). *75mm To Hit Number -1. Turret gun and other weapon stats not specified on card."
    },
    {
      "num": 34,
      "name": "CHAR B1-bis (CE)",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": 9,
      "button_up": false,
      "bog": "5/w0",
      "morale": 4,
      "points": 315,
      "armor": "i3/s4/k5",
      "flank": "i1/s2/k3",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun (75mm)",
        "effect_number": 4,
        "alternate_effect_number": 2,
        "second_alternate_effect_number": 2,
        "third_alternate_effect_number": 2,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [3,4,5,6,7,8]
      },
      "notes": "Pinned requires Rally 3 (Inferred). *75mm To Hit Number -1. Turret gun and other weapon stats not specified on card."
    },
    {
      "num": 35,
      "name": "AMD 35 (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "3/w6",
      "morale": 4,
      "points": 232,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "alternate_effect_number": 0,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [2,3,3,4,4,5]
      },
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 35,
      "name": "AMD 35 (CE)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "4/w7",
      "morale": 4,
      "points": 232,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "alternate_effect_number": 0,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2,3,4,5,6,7]
      },
      "notes": "Pinned requires Rally 3 (Inferred)."
    }
  ]
};