window.germanyData = {
  "name": "Germany",
  "hand_capacity": 5,
  "discard": 1,
  "discard_condition_no_action": false,
  "notes": "May discard up to 1 card on Player.",
  "broken_squad": 50,
  "nationalTactics": {
    "priorityModifiers": {
      "FIRE_HIGH_OPP": 1.2,        // Germans love their MGs
      "FIRE_OPP": 1.1,             // General fire preference
      "ENTRENCH": 1.1,             // Defensive mindset
      "RALLY_ALL": 1.3,            // Maintain command structure
      "RALLY_NUM": 1.2,            // Leadership focus
      "FIX_WEAPON": 1.1            // Equipment maintenance
    },
    "description": "German tactics emphasize superior firepower, defensive positions, and maintaining command structure."
  },
  "units": [
    {
      "id": -1,
      "num": 1,
      "name": "SGT DIETTINGER",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 5,
      "sl": true,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Machine Pistol - MP 38",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 5,
      "morale_boxed": null,
      "points": 51,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 6,
      "panic_boxed": null,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 6,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": null
    },
    {
      "id": -1,
      "num": 2,
      "name": "CPL HESSEL",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": true,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Machine Pistol - MP 38",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 4,
      "morale_boxed": null,
      "points": 41,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 5,
      "panic_boxed": null,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 5,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": null
    },
    {
      "id": -1,
      "num": 3,
      "name": "PFC SCHUSSEL",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Light Machinegun",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 4,
      "fp_range_1": 5,
      "fp_range_2": 6,
      "fp_range_3": 7,
      "fp_range_4": 8,
      "fp_range_5": 9,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": {
        "type": "LMG",
        "sustained_fp_0": 2,
        "sustained_fp_1": 3,
        "sustained_fp_2": 3,
        "sustained_fp_3": 4,
        "sustained_fp_4": 4,
        "sustained_fp_5": 5
      },
      "morale": 3,
      "morale_boxed": null,
      "points": 54,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 4,
      "panic_boxed": null,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 4,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": null
    },
    {
      "id": -1,
      "num": 4,
      "name": "PVT SCHUMACHER",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Bolt Action Rifle",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 3,
      "morale_boxed": null,
      "points": 15,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 4,
      "panic_boxed": null,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 4,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": null
    },
    {
      "id": -1,
      "num": 5,
      "name": "PVT SCHULTZ",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Bolt Action Rifle",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 2,
      "morale_boxed": null,
      "points": 10,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 3,
      "panic_boxed": null,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 3,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": null
    },
    {
      "id": -1,
      "num": 6,
      "name": "PVT BERNHOFF",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Bolt Action Rifle",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 5,
      "morale_boxed": null,
      "points": 25,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 6,
      "panic_boxed": null,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 6,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": null
    },
    {
      "id": -1,
      "num": 7,
      "name": "PVT BECK",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Bolt Action Rifle",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 1,
      "morale_boxed": null,
      "points": 5,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 2,
      "panic_boxed": null,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 2,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": null
    },
    {
      "id": -1,
      "num": 8,
      "name": "PVT WOLLAK",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Bolt Action Rifle",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 2,
      "morale_boxed": null,
      "points": 8,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 2,
      "panic_boxed": null,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 2,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": null
    },
    {
      "id": -1,
      "num": 9,
      "name": "PVT STREICH",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Bolt Action Rifle",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 3,
      "morale_boxed": null,
      "points": 13,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 3,
      "panic_boxed": null,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 3,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": null
    },
    {
      "id": -1,
      "num": 10,
      "name": "PVT WOLFF",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Bolt Action Rifle",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 4,
      "morale_boxed": null,
      "points": 17,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 4,
      "panic_boxed": null,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 4,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": null
    },
    {
      "id": -1,
      "num": 11,
      "name": "PFC GERHART",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "Panzerschreck",
      "weapon_secondary": null,
      "effect_num": 3,
      "effect_num_boxed": 4,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": 4,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
       "weapon_details": {
           "type": "Panzerschreck",
           "range_3_th": "0-1 [2]",
           "range_4_th": "0-2 [0]",
           "range_5_th": "0-3 [0-1]",
           "ammo": null,
           "notes": ["No Secondary Weapons Allowed"]
       },
      "morale": 4,
      "morale_boxed": null,
      "points": 89,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 5,
      "panic_boxed": null,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 5,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false, // Card doesn't explicitly say No Moving Fire, typical for Bazooka/Panzerschreck
      "no_secondary_weapons": true,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Breakdown notation: [X3-6] X4-6 (Using 6, Alt 4 for representation)."
    },
    {
      "id": -1,
      "num": 21,
      "name": "PVT HAMBLEN",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "MP 38",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 1,
      "morale_boxed": null,
      "points": 5,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 2,
      "panic_boxed": null,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 2,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Sketch KIA Pinned (9) conflicts with Weapon card (8)."
    },
    {
      "id": -1,
      "num": 22,
      "name": "PVT LOTH",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "MP 38",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 2,
      "morale_boxed": null,
      "points": 11,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 3,
      "panic_boxed": null,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 3,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Sketch KIA Pinned (9) conflicts with Weapon card (8)."
    },
    {
      "id": -1,
      "num": 23,
      "name": "SGT STAHLER",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 4,
      "sl": true,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "MP 38",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 4,
      "morale_boxed": null,
      "points": 46,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 5,
      "panic_boxed": null,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 5,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Reduced Hand Capacity. Sketch KIA Pinned (9) conflicts with Weapon card (8)."
    },
    {
      "id": -1,
      "num": 24,
      "name": "CPL STEINER",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": true,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "MP 38",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 3,
      "morale_boxed": null,
      "points": 36,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 4,
      "panic_boxed": null,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 4,
      "rally": null,
      "pinned_rule": null,
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Reduced Hand Capacity if SL. Sketch KIA Pinned (9) conflicts with Weapon card (8)."
    },
     {
      "id": -1,
      "num": 25,
      "name": "PFC BAUER",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "50mm Mortar",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": 4,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": {
           "type": "Mortar",
           "range_0_th": "0 [2]",
           "range_1_th": "0-1 [1]",
           "range_2_th": "0-2 [0]",
           "range_3_th": "0-3 [0-1]",
           "range_4_th": "0-3 [0-1]",
           "range_5_fp": 1,
           "ammo": null,
           "notes": ["No Secondary Weapons Allowed", "No Moving Fire"]
       },
      "morale": 3,
      "morale_boxed": null,
      "points": 60,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 4,
      "panic_boxed": null,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 4,
      "rally": null,
      "pinned_rule": null,
      "available": "1941-1943",
      "no_moving_fire": true,
      "no_secondary_weapons": true,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Breakdown notation: [X4-6] X5-6. Sketch KIA Pinned (9) conflicts with Weapon card (8)."
    },
    {
      "id": -1,
      "num": 26,
      "name": "PVT KUBLER",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "StG 44 / MP43",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 5,
      "morale_boxed": null,
      "points": 30,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 5,
      "panic_boxed": null,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 5,
      "rally": null,
      "pinned_rule": null,
      "available": "1944-1945",
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Available 1944-1945. Sketch KIA Pinned (9) conflicts with Weapon card (8)."
    },
    {
      "id": -1,
      "num": 27,
      "name": "PVT KLAPP",
      "assault_gun": false,
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "bog_column": -1,
      "bog_column_wire": -1,
      "weapon": "StG 44 / MP43",
      "weapon_secondary": null,
      "effect_num": null,
      "effect_num_boxed": null,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": null,
      "fp_range_0": 0,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": null,
      "morale": 2,
      "morale_boxed": null,
      "points": 14,
      "kia_unpinned": 8,
      "kia_unpinned_boxed": null,
      "armor": null,
      "flank": null,
      "panic": 3,
      "panic_boxed": null,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "kia_pinned_boxed": null,
      "rout": 3,
      "rally": null,
      "pinned_rule": null,
      "available": "1944-1945",
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Available 1944-1945. Sketch KIA Pinned (9) conflicts with Weapon card (8)."
    },
    {
      "id": -1,
      "num": 28,
      "name": "37mm PAK 36",
      "assault_gun": false,
      "card_type": "Support Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "bog_column": null,
      "bog_column_wire": null,
      "weapon": "37mm PAK 36",
      "weapon_secondary": null,
      "effect_num": 1,
      "effect_num_boxed": 1,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
      "to_hit_range_0": "1",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": ["No Moving Fire"]
      },
      "morale": 5,
      "morale_boxed": 3,
      "points": 213,
      "kia_unpinned": 9,
      "kia_unpinned_boxed": 7,
      "armor": null,
      "flank": null,
      "panic": 6,
      "panic_boxed": 4,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "kia_pinned_boxed": 7,
      "rout": 6,
      "rally": 3,
      "pinned_rule": "requires Rally 3",
      "available": null,
      "no_moving_fire": true,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1, // Assuming support weapons move like men unless noted
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Breakdown notation: X5-6."
    },
    {
      "id": -1,
      "num": 29,
      "name": "50mm PAK 38",
      "assault_gun": false,
      "card_type": "Support Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "bog_column": null,
      "bog_column_wire": null,
      "weapon": "50mm PAK 38",
      "weapon_secondary": null,
      "effect_num": 2,
      "effect_num_boxed": 3,
      "overrun": null,
      "ce_defense": null,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": ["No Moving Fire"]
      },
      "morale": 5,
      "morale_boxed": 3,
      "points": 265,
      "kia_unpinned": 9,
      "kia_unpinned_boxed": 7,
      "armor": null,
      "flank": null,
      "panic": 6,
      "panic_boxed": 4,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "kia_pinned_boxed": 7,
      "rout": 6,
      "rally": 3,
      "pinned_rule": "requires Rally 3",
      "available": null,
      "no_moving_fire": true,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": 1, // Assuming support weapons move like men unless noted
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Breakdown notation: X5-6."
    },
    {
      "id": -1,
      "num": 30,
      "name": "SPW 251/1",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 4,
      "bog_column_wire": 7,
      "weapon": "M2 HMG + MG 34/42",
      "weapon_secondary": null,
      "effect_num": 4,
      "effect_num_boxed": null,
      "overrun": 3,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 8,
      "fp_range_1": 9,
      "fp_range_2": 10,
      "fp_range_3": 11,
      "fp_range_4": 12,
      "fp_range_5": 13,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": {
        "type": "MG",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 202,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": null, "s": 0, "k": 1 },
      "flank": { "i": -1, "s": 0, "k": 0 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": 3,
      "pinned_rule": "Requires Rally 3",
      "available": null,
      "no_moving_fire": false,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Breakdown notation: X5-6."
    },
    {
      "id": -1,
      "num": 31,
      "name": "SdKfz 231",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 5,
      "bog_column_wire": 8,
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 1,
      "effect_num_boxed": 0,
      "overrun": 2,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 6,
      "fp_range_5": 7,
      "to_hit_range_0": "2",
      "to_hit_range_1": "1",
      "to_hit_range_2": "0-1",
      "to_hit_range_3": "0-2",
      "to_hit_range_4": "0-3",
      "to_hit_range_5": "0-4",
      "weapon_details": {
        "type": "Gun",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 267,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": null, "s": 1, "k": 2 },
      "flank": { "i": -1, "s": 0, "k": 0 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null,
      "pinned_rule": null, // Sketch implies Button Up instead
      "available": null,
      "no_moving_fire": false, // Not explicitly stated, assume standard rules apply
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6."
    },
    {
      "id": -1,
      "num": 32,
      "name": "PzKw IIIH",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 6,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 2,
      "effect_num_boxed": 3,
      "overrun": 2,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 4,
      "fp_range_1": 5,
      "fp_range_2": 6,
      "fp_range_3": 7,
      "fp_range_4": 8,
      "fp_range_5": 9,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 402,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": null, "s": 4, "k": 5 },
      "flank": { "i": null, "s": 2, "k": 3 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "1941-1942",
      "no_moving_fire": false, // Not explicitly stated, assume standard rules apply
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch OVR (1) and BOG (5/w9) conflict with Weapon card (OVR 2, BOG 6/w0)."
    },
    {
      "id": -1,
      "num": 33,
      "name": "PzKw IVH",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 6,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 4,
      "effect_num_boxed": 5,
      "overrun": 4,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 8,
      "fp_range_1": 9,
      "fp_range_2": 10,
      "fp_range_3": 11,
      "fp_range_4": 12,
      "fp_range_5": 13,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 523,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": null, "s": 5, "k": 6 },
      "flank": { "i": null, "s": 2, "k": 3 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "8/1942-1945",
      "no_moving_fire": false, // Not explicitly stated, assume standard rules apply
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch OVR (2) and BOG (5/w9) conflict with Weapon card (OVR 4, BOG 6/w0)."
    },
    {
      "id": -1,
      "num": 34,
      "name": "PzKw VG PANTHER",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 6,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 4,
      "effect_num_boxed": 7,
      "overrun": 4,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 8,
      "fp_range_1": 9,
      "fp_range_2": 10,
      "fp_range_3": 11,
      "fp_range_4": 12,
      "fp_range_5": 13,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 607,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": 7, "s": 8, "k": 9 },
      "flank": { "i": null, "s": 4, "k": 5 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "1944",
      "no_moving_fire": false, // Not explicitly stated, assume standard rules apply
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch OVR (2) and BOG (5/w9) conflict with Weapon card (OVR 4, BOG 6/w0)."
    },
    {
      "id": -1,
      "num": 35,
      "name": "PzKw VIB KING TIGER",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 3,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 5,
      "effect_num_boxed": 8,
      "overrun": 4,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 8,
      "fp_range_1": 9,
      "fp_range_2": 10,
      "fp_range_3": 11,
      "fp_range_4": 12,
      "fp_range_5": 13,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 656,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": 9, "s": 10, "k": 11 },
      "flank": { "i": 4, "s": 5, "k": 6 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "JUNE 1944 E.Front, AUGUST 1944 W.Front",
      "no_moving_fire": false, // Not explicitly stated, assume standard rules apply
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch OVR (2) and BOG (2/w9) conflict with Weapon card (OVR 4, BOG 3/w0)."
    },
    {
      "id": -1,
      "num": 36,
      "name": "PzKw VIE TIGER",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 4,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 5,
      "effect_num_boxed": 6,
      "overrun": 3,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 4,
      "fp_range_1": 5,
      "fp_range_2": 6,
      "fp_range_3": 7,
      "fp_range_4": 8,
      "fp_range_5": 9,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 560,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": 5, "s": 6, "k": 7 },
      "flank": { "i": 4, "s": 5, "k": 6 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "SEPTEMBER 1942 E.Front, DECEMBER 1942 W.Front",
      "no_moving_fire": false, // Not explicitly stated, assume standard rules apply
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch OVR (2) and BOG (3/w9) conflict with Weapon card (OVR 3, BOG 4/w0)."
    },
    {
      "id": -1,
      "num": 37,
      "name": "PzKw IIF",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 7,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 1,
      "effect_num_boxed": 0,
      "overrun": 2,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 6,
      "fp_range_5": 7,
      "to_hit_range_0": "2",
      "to_hit_range_1": "1",
      "to_hit_range_2": "0-1",
      "to_hit_range_3": "0-2",
      "to_hit_range_4": "0-3",
      "to_hit_range_5": "0-4",
      "weapon_details": {
        "type": "Gun",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 299,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": null, "s": 2, "k": 3 },
      "flank": { "i": null, "s": 0, "k": 1 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "1941-1943",
      "no_moving_fire": false, // Not explicitly stated, assume standard rules apply
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch OVR (1) and BOG (7/w9) conflict with Weapon card (OVR 2, BOG 7/w0)."
    },
    {
      "id": -1,
      "num": 38,
      "name": "PzKw II (F1) Flamethrower",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 7,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Flamethrower + MG",
      "weapon_secondary": null,
      "effect_num": 6,
      "effect_num_boxed": 9,
      "overrun": 5,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 0, // FP ranges for MG only, FT is separate
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": {
           "type": "Flamethrower",
           "ft_fp_range_5": 14,
           "ft_fp_range_5_boxed": 7,
           "mg_fp_ranges": [2, 3, 4, 5, 6, 7],
           "notes": ["No Defensive TEM", "No FF Bonus", "Moving Fire not Halved"]
       },
      "morale": 5,
      "morale_boxed": null,
      "points": 247,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": null, "s": 2, "k": 3 },
      "flank": { "i": null, "s": 0, "k": 1 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null,
      "pinned_rule": null, // Sketch implies Button Up instead
      "available": "6/42 vs Russia Only",
      "no_moving_fire": false, // Handled by moving_fire_not_halved in weapon_details notes
      "no_secondary_weapons": false, // Not explicitly stated, assume standard rules apply
      "moving_fire_not_halved": true,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch BOG (6/w9) conflicts with Weapon card (7/w0)."
    },
    {
      "id": -1,
      "num": 39,
      "name": "StuG IIIB",
      "assault_gun": true,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 5,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 4,
      "effect_num_boxed": 2,
      "overrun": null,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 6,
      "fp_range_1": 7,
      "fp_range_2": 8,
      "fp_range_3": 9,
      "fp_range_4": 10,
      "fp_range_5": 11,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": ["No Moving Fire Allowed"]
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 361,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": 3, "s": 4, "k": 5 },
      "flank": { "i": 1, "s": 2, "k": 3 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "5/1940-1943",
      "no_moving_fire": true,
      "no_secondary_weapons": false, // Not explicitly stated, assume standard rules apply
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0, // Handled by +1 note
      "th_vs_moving_target_modifier": 1,
      "th_if_bogged_immobilized_modifier": 2,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch BOG (4/w9) conflicts with Weapon card (5/w0). Weapon card 'No Moving Fire Allowed' contradicts sketch 'Moving Target' modifier."
    },
    {
      "id": -1,
      "num": 40,
      "name": "StuG IIIG",
      "assault_gun": true,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 4,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 4,
      "effect_num_boxed": 5,
      "overrun": 3,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 6,
      "fp_range_1": 7,
      "fp_range_2": 8,
      "fp_range_3": 9,
      "fp_range_4": 10,
      "fp_range_5": 11,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": ["No Moving Fire Allowed"]
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 446,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": 4, "s": 5, "k": 6 },
      "flank": { "i": 1, "s": 2, "k": 3 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "JUNE 1942",
      "no_moving_fire": true,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0, // Handled by +1 note
      "th_vs_moving_target_modifier": 1,
      "th_if_bogged_immobilized_modifier": 2,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch OVR (2) and BOG (3/w9) conflict with Weapon card (OVR 3, BOG 4/w0). Weapon card 'No Moving Fire Allowed' contradicts sketch 'Moving Target' modifier."
    },
    {
      "id": -1,
      "num": 41,
      "name": "PzKw III (F1) Flamethrower",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 5,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Flamethrower + MG",
      "weapon_secondary": null,
      "effect_num": 5,
      "effect_num_boxed": null, // Boxed 1 on sketch, but weapon card has EN 5, OVR 5. Use weapon card EN/OVR.
      "overrun": 5,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 0, // FP ranges for MG only, FT is separate
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
      "to_hit_range_0": null,
      "to_hit_range_1": null,
      "to_hit_range_2": null,
      "to_hit_range_3": null,
      "to_hit_range_4": null,
      "to_hit_range_5": null,
      "weapon_details": {
           "type": "Flamethrower",
           "ft_fp_range_5": 14,
           "ft_fp_range_5_boxed": 7,
           "mg_fp_ranges": [4, 5, 6, 7, 8, 9],
           "notes": ["No Defensive TEM", "No FF Bonus", "Moving Fire not Halved"]
       },
      "morale": 5,
      "morale_boxed": null,
      "points": 386,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": 4, "s": 5, "k": 6 },
      "flank": { "i": 1, "s": 2, "k": 3 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null,
      "pinned_rule": null, // Sketch implies Button Up instead
      "available": "7/43-1945",
      "no_moving_fire": false, // Handled by moving_fire_not_halved in weapon_details notes
      "no_secondary_weapons": false, // Not explicitly stated, assume standard rules apply
      "moving_fire_not_halved": true,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0, // Handled by +1 note
      "th_vs_moving_target_modifier": 1,
      "th_if_bogged_immobilized_modifier": 0, // Not listed, assume 0
      "notes": "Button Up. Breakdown notation: X5-6. Sketch EN (1 [1]) and BOG (4/w9) conflict with Weapon card (EN 5, BOG 5/w0)."
    },
    {
      "id": -1,
      "num": 42,
      "name": "PSW 234/2 PUMA",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 5,
      "bog_column_wire": 7,
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 2,
      "effect_num_boxed": 3,
      "overrun": 2,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 6,
      "fp_range_5": 7,
      "to_hit_range_0": "2",
      "to_hit_range_1": "1",
      "to_hit_range_2": "0-1",
      "to_hit_range_3": "0-2",
      "to_hit_range_4": "0-3",
      "to_hit_range_5": "0-4",
      "weapon_details": {
        "type": "Gun",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 367,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": 2, "s": 3, "k": 4 },
      "flank": { "i": -1, "s": 0, "k": 1 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "10/1943-1945",
      "no_moving_fire": false, // Not explicitly stated, assume standard rules apply
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch OVR (1) and BOG (4/w6) conflict with Weapon card (OVR 2, BOG 5/w7)."
    },
    {
      "id": -1,
      "num": 43,
      "name": "PzKw 38(t)E",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 0,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 1,
      "effect_num_boxed": 1,
      "overrun": 2,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 4,
      "fp_range_1": 5,
      "fp_range_2": 6,
      "fp_range_3": 7,
      "fp_range_4": 8,
      "fp_range_5": 9,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 364,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": 3, "s": 4, "k": 5 },
      "flank": { "i": 0, "s": 1, "k": 2 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "1941-1942",
      "no_moving_fire": false, // Not explicitly stated, assume standard rules apply
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch OVR (1) and BOG (9/w9) conflict with Weapon card (OVR 2, BOG 0/w0)."
    },
    {
      "id": -1,
      "num": 44,
      "name": "PzKw IIIN",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 6,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 4,
      "effect_num_boxed": 2,
      "overrun": 3,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 4,
      "fp_range_1": 5,
      "fp_range_2": 6,
      "fp_range_3": 7,
      "fp_range_4": 8,
      "fp_range_5": 9,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": []
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 467,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": 4, "s": 5, "k": 6 },
      "flank": { "i": 1, "s": 2, "k": 3 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "9/1942-1945",
      "no_moving_fire": false, // Not explicitly stated, assume standard rules apply
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0,
      "th_vs_moving_target_modifier": 0,
      "th_if_bogged_immobilized_modifier": 0,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch OVR (2) and BOG (5/w9) conflict with Weapon card (OVR 3, BOG 6/w0)."
    },
    {
      "id": -1,
      "num": 45,
      "name": "Jagd Pz 38(t) HETZER",
      "assault_gun": true,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 7,
      "bog_column_wire": 0, // Bog w/o wire same as Bog
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 4,
      "effect_num_boxed": 5,
      "overrun": 2,
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 6,
      "fp_range_5": 7,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": ["No Moving Fire Allowed"]
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 476,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": 6, "s": 7, "k": 8 },
      "flank": { "i": 1, "s": 2, "k": 3 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": null, // Not on card
      "pinned_rule": null, // Not on card (sketch implies Button Up)
      "available": "JULY 1944",
      "no_moving_fire": true,
      "no_secondary_weapons": false,
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0, // Handled by +1 note
      "th_vs_moving_target_modifier": 1,
      "th_if_bogged_immobilized_modifier": 2,
      "notes": "Button Up. Breakdown notation: X5-6. Sketch BOG (6/w9) conflicts with Weapon card (7/w0). Weapon card 'No Moving Fire Allowed' contradicts sketch 'Moving Target' modifier."
    },
    {
      "id": -1,
      "num": 46,
      "name": "SPW 251/10",
      "assault_gun": false,
      "card_type": "Vehicle",
      "ccv_unpinned_armed": null,
      "ccv_unpinned_unarmed": null,
      "sl": false,
      "asl": false,
      "bog_column": 4,
      "bog_column_wire": 7,
      "weapon": "Main Gun + MG",
      "weapon_secondary": null,
      "effect_num": 1,
      "effect_num_boxed": 1,
      "overrun": null, // OVR is NA on card
      "ce_defense": 9,
      "breakdown": 6,
      "breakdown_alt": 5,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 0,
      "fp_range_4": 0,
      "fp_range_5": 0,
      "to_hit_range_0": "0",
      "to_hit_range_1": "0-1",
      "to_hit_range_2": "0-2",
      "to_hit_range_3": "0-3",
      "to_hit_range_4": "0-4",
      "to_hit_range_5": "0-5",
      "weapon_details": {
        "type": "Gun",
        "notes": ["No Moving Fire Allowed"]
      },
      "morale": 5,
      "morale_boxed": null,
      "points": 173,
      "kia_unpinned": null,
      "kia_unpinned_boxed": null,
      "armor": { "i": null, "s": 0, "k": 1 },
      "flank": { "i": -1, "s": 0, "k": 0 },
      "panic": null,
      "panic_boxed": null,
      "ccv_pinned_armed": null,
      "ccv_pinned_unarmed": null,
      "kia_pinned": null,
      "kia_pinned_boxed": null,
      "rout": null,
      "rally": 3,
      "pinned_rule": "Requires Rally 3",
      "available": null, // Not explicitly stated on card
      "no_moving_fire": true,
      "no_secondary_weapons": false, // Not explicitly stated, assume standard rules apply
      "moving_fire_not_halved": false,
      "num_men_to_move": null,
      "th_if_flanking_target_group_modifier": 0, // Handled by +1 note
      "th_vs_moving_target_modifier": 1,
      "th_if_bogged_immobilized_modifier": 2,
      "notes": "Breakdown notation: X5-6. Sketch MG (X6) conflicts with Weapon card (X5-6). OVR is NA."
    }
  ]
};