window.italyData = {
  "name": "Italy",
  "hand_capacity": 4,
  "discard": 2,
  "discard_condition_no_action": true,
  "notes": "May discard up to 2 cards on Player.",
  "broken_squad": 40,
  "units": [
    {
      "num": 1,
      "name": "SGT FERRARO",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": true,
      "asl": false,
      "weapon": "Beretta M 38-A",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
        "type": "Machine Pistol"
      },
      "morale": 3,
      "points": 36,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity. ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 2,
      "name": "CPL ANTONIO",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": true,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 4,
      "points": 32,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity if SL. ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 3,
      "name": "PFC CAPITANO",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Breda Mod 30",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 5,
      "fp_range_5": 6,
      "weapon_details": {
        "type": "Light Machinegun"
      },
      "morale": 4,
      "points": 33,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 4,
      "name": "PVT SARDUCCI",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 4,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 5,
      "name": "PVT NARDO",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 5,
      "kia_unpinned": 8,
      "panic": 1,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 6,
      "name": "PVT ABRUZZI",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 9,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 7,
      "name": "PVT MARINO",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 7,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 8,
      "name": "PVT PAOLINI",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 5,
      "points": 12,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 9,
      "name": "PFC NAPOLI",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Breda Mod 30",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 5,
      "fp_range_5": 6,
      "weapon_details": {
        "type": "Light Machinegun"
      },
      "morale": 3,
      "points": 30,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 10,
      "name": "PVT CELOZZI",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 6,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 11,
      "name": "PVT GIORGIO",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 7,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 12,
      "name": "PVT PASINI",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 9,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 13,
      "name": "PVT FARINACCI",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 3,
      "points": 7,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 14,
      "name": "PVT GIONELLI",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 6,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 15,
      "name": "PVT CIAPPI",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 5,
      "kia_unpinned": 8,
      "panic": 1,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 16,
      "name": "PVT NATALE",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 6,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 17,
      "name": "PVT COSTANZI",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 5,
      "kia_unpinned": 8,
      "panic": 1,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 18,
      "name": "PVT GIGANTI",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 4,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 19,
      "name": "PVT ROMANO",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 1,
      "points": 3,
      "kia_unpinned": 8,
      "panic": 1,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 20,
      "name": "PVT MOSELLI",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 1,
      "points": 2,
      "kia_unpinned": 8,
      "panic": 0,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": null,
      "notes": "PANIC: 0. ROUT: unless KIA."
    },
    {
      "num": 21,
      "name": "SGT CAPONE",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 4,
      "sl": true,
      "asl": false,
      "weapon": "Beretta M 38-A",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
        "type": "Machine Pistol"
      },
      "morale": 4,
      "points": 39,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity. ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 22,
      "name": "CPL FARRIO",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": true,
      "weapon": "Beretta M 38-A",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
        "type": "Machine Pistol"
      },
      "morale": 3,
      "points": 31,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity if SL. ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 23,
      "name": "PVT CORRERI",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 6,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 24,
      "name": "PVT TIOLLE",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mannlicher Carcano M 91/41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "weapon_details": {
        "type": "Bolt-Action Rifle"
      },
      "morale": 2,
      "points": 5,
      "kia_unpinned": 8,
      "panic": 1,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 25,
      "name": "PFC GIOVINO",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "morale": 3,
      "morale_pinned": 3,
      "points": 35,
      "kia_unpinned": 8,
      "panic": 3,
      "panic_pinned": 3,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "weapon_details": {
        "type": "Mortar",
        "name": "Mod 35 Brixia",
        "effect_number": 1,
        "breakdown": 6,
        "to_hit_ranges": ["0 [2]", "0-1 [1]", "0-2 [0]", "0-3 [0-1]", "0-3 [0-1]", null],
        "fp_ranges": [null, null, null, null, null, "2FP"],
        "no_moving_fire": true
      },
      "notes": "No Secondary Weapons Allowed. No Moving Fire. Breakdown: [X4-6] X5-6. ROUT: 0r RNC > 2 / BERSERK: (RR5) 0r RNC <= 2"
    },
    {
      "num": 26,
      "name": "PFC LEONE",
      "card_type": "Man",
      "ccv_unpinned_armed": 2,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Lanciafiamme M 40",
      "breakdown": 6,
      "fp_range_0": null,
      "fp_range_1": null,
      "fp_range_2": null,
      "fp_range_3": null,
      "fp_range_4": null,
      "fp_range_5": 12,
      "weapon_details": {
        "type": "Flamethrower",
        "range": 5,
        "fp": 12,
        "no_def_tem": true,
        "no_ff_inf_bonus": true,
        "moving_fire_not_halved": true
      },
      "morale": 3,
      "points": 30,
      "kia_unpinned": 7,
      "panic": 2,
      "ccv_pinned_armed": -2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 8,
      "rout": null,
      "notes": "* No Def TEM, No FF/INF Bonus. * Moving Fire Not Halved. No Secondary Weapons Allowed. Breakdown: X5-6. ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 27,
      "name": "PFC SALVADORI",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Fiat Revelli M 35",
      "breakdown": 6,
      "fp_range_0": 6,
      "fp_range_1": 7,
      "fp_range_2": 8,
      "fp_range_3": 9,
      "fp_range_4": 10,
      "fp_range_5": 11,
      "weapon_details": {
        "type": "MMG",
        "sustained_fp_0": 3,
        "sustained_fp_1": 4,
        "sustained_fp_2": 4,
        "sustained_fp_3": 5,
        "sustained_fp_4": 5,
        "sustained_fp_5": 6,
        "no_moving_fire": true
      },
      "morale": 3,
      "points": 52,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. No Moving Fire. Breakdown: [X4-6] X5-6. ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 28,
      "name": "PFC RITONDO",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Solothurn 20mm",
      "breakdown": 6,
      "fp_range_0": 1,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 1,
      "fp_range_4": 1,
      "fp_range_5": 1,
      "weapon_details": {
        "type": "Anti-Tank Rifle",
        "effect_number": 0,
        "to_hit_ranges": ["4 [5]", "3 [4]", "3 [4]", "2 [3]", "2 [3]", "1 [2]"],
        "flank_bonus": -1,
        "no_moving_fire": true
      },
      "morale": 3,
      "points": 9,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. No Moving Fire, 2 Men to Move. Breakdown: [X5-6] X6. ROUT: 0r RNC > 1 / BERSERK: (RR5) 0r RNC <= 1"
    },
    {
      "num": 29,
      "name": "20mm ATG M35",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 113,
      "kia_unpinned": 9,
      "panic": 4,
      "panic_pinned": 2,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": null,
      "weapon_details": {
        "type": "AT Gun",
        "effect_number": 1,
        "alternate_effect_number": 0,
        "breakdown": 6,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. No Moving Fire. Breakdown: X4-6. ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 30,
      "name": "47mm ATG M35",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 163,
      "kia_unpinned": 9,
      "panic": 4,
      "panic_pinned": 2,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": null,
      "weapon_details": {
        "type": "AT Gun",
        "effect_number": 2,
        "alternate_effect_number": 2,
        "breakdown": 6,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. No Moving Fire. ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 31,
      "name": "L3/35 (Button Up)",
      "card_type": "Vehicle",
      "ovr": 0,
      "ce": null,
      "button_up": true,
      "bog": "5/w7",
      "morale": 3,
      "points": 90,
      "armor": "i:s0/k1",
      "flank": "i:s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Machine Gun",
        "fp_ranges": [2,3,3,4,4,5]
      },
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 31,
      "name": "L3/35 (CE)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": 9,
      "button_up": false,
      "bog": "6/w8",
      "morale": 3,
      "points": 90,
      "armor": "i:s0/k1",
      "flank": "i:s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Machine Gun",
        "fp_ranges": [3,4,5,6,7,8]
      },
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 32,
      "name": "L3/Lf (Button Up)",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": null,
      "button_up": true,
      "bog": "3/w6",
      "morale": 3,
      "points": 120,
      "armor": "i:s0/k1",
      "flank": "i:s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "flamethrower_details": {
        "type": "Flamethrower",
        "range": 4,
        "fp": 10,
        "no_def_tem": true,
        "no_ff_inf_bonus": true,
        "moving_fire_not_halved": true
      },
      "mg_fp_ranges": [1,2,2,3,3,4],
      "notes": "* No Defensive TEM, No FF Bonus. * Moving Fire not Halved. Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 32,
      "name": "L3/Lf (CE)",
      "card_type": "Vehicle",
      "ovr": 4,
      "ce": 9,
      "button_up": false,
      "bog": "5/w7",
      "morale": 3,
      "points": 120,
      "armor": "i:s0/k1",
      "flank": "i:s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "flamethrower_details": {
        "type": "Flamethrower",
        "range": 4,
        "fp": 14,
        "no_def_tem": true,
        "no_ff_inf_bonus": true,
        "moving_fire_not_halved": true
      },
      "mg_fp_ranges": [2,3,3,4,4,5],
      "notes": "* No Defensive TEM, No FF Bonus. * Moving Fire not Halved. Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 33,
      "name": "M13/40 (Button Up)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": null,
      "button_up": true,
      "bog": "5/w9",
      "morale": 3,
      "points": 220,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 2,
        "alternate_effect_number": 2,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [4,5,5,6,6,7]
      },
      "available": "DECEMBER 1940",
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 33,
      "name": "M13/40 (CE)",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": 9,
      "button_up": false,
      "bog": "6/w0",
      "morale": 3,
      "points": 220,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 2,
        "alternate_effect_number": 2,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [5,6,7,8,9,10]
      },
      "available": "DECEMBER 1940",
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 34,
      "name": "SEMOVENTE M41 (Button Up)",
      "card_type": "Vehicle",
      "ovr": null,
      "ce": null,
      "button_up": true,
      "bog": "5/w8",
      "morale": 3,
      "points": 223,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "alternate_effect_number": 2,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [2,3,4,5,6,7],
        "no_moving_fire": true
      },
      "available": "MARCH 1942",
      "notes": "No Moving Fire Allowed. +1 To Hit vs Moving Target. +2 To Hit if Bogged / Immobilized. Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 34,
      "name": "SEMOVENTE M41 (CE)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "5/w8",
      "morale": 3,
      "points": 223,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "alternate_effect_number": 2,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2,3,4,5,6,7],
        "no_moving_fire": true
      },
      "available": "MARCH 1942",
      "notes": "No Moving Fire Allowed. +1 To Hit vs Moving Target. +2 To Hit if Bogged / Immobilized. Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 35,
      "name": "ANSALDO AB 41 (Button Up)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "3/w6",
      "morale": 3,
      "points": 162,
      "armor": "i:s-1/k0",
      "flank": "i:s-2/k-1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "alternate_effect_number": 0,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [1,2,2,3,3,4]
      },
      "available": "1941",
      "notes": "Pinned requires Rally 3 (Inferred)."
    },
    {
      "num": 35,
      "name": "ANSALDO AB 41 (CE)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "4/w7",
      "morale": 3,
      "points": 162,
      "armor": "i:s-1/k0",
      "flank": "i:s-2/k-1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "alternate_effect_number": 0,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2,3,4,5,6,7]
      },
      "available": "1941",
      "notes": "Pinned requires Rally 3 (Inferred)."
    }
  ]
};