window.japanData = {
  "name": "Japan",
  "hand_capacity": 4,
  "discard": 2,
  "discard_condition_no_action": true,
  "notes": "May discard up to 2 cards on Player.",
  "broken_squad": 75,
  "nationalTactics": {
    "priorityModifiers": {
      "BANZAI": 2.0,               // Signature tactic
      "INFILTRATE_MORALE": 1.3,    // Stealth tactics
      "INFILTRATE_MOVE": 1.2,      // Night fighting
      "MOVE_ADVANCE": 1.2,         // Aggressive spirit
      "ENTRENCH": 0.7,             // Less static defense
      "MOVE_RETREAT": 0.5,         // Never retreat
      "FIRE_INFILTRATE": 1.3,      // Surprise attacks
      "LAY_SMOKE": 1.1             // Concealment tactics
    },
    "description": "Japanese tactics emphasize Banzai charges, infiltration, and refusal to retreat."
  },
  "units": [
    {
      "num": 1,
      "name": "SGT OKIMOTO",
      "card_type": "Man",
      "ccv_unpinned_armed": 11,
      "ccv_unpinned_unarmed": 6,
      "sl": true,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 6,
      "points": 46,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 7,
      "ccv_pinned_unarmed": 2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity. ROUT: 0r RNC > 8 / BERSERK: (RR5) 0r RNC <= 8"
    },
    {
      "num": 2,
      "name": "CPL TOGO",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": true,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 5,
      "points": 37,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity if SL. ROUT: 0r RNC > 7 / BERSERK: (RR5) 0r RNC <= 7"
    },
    {
      "num": 3,
      "name": "PFC YORUBA",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Nambu Type 11",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 6,
      "fp_range_5": 6,
      "weapon_details": {
        "type": "LMG"
      },
      "morale": 4,
      "points": 47,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 4,
      "name": "PVT KOBAYASHI",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 5,
      "points": 17,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 7 / BERSERK: (RR5) 0r RNC <= 7"
    },
    {
      "num": 5,
      "name": "PVT TOGAMI",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 6,
      "name": "PVT FUJIYAMA",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 4,
      "points": 13,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 7,
      "name": "PVT ASANTI",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 4,
      "points": 13,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 8,
      "name": "PVT SAKAI",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 9,
      "name": "PVT FUCHIDA",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 2,
      "points": 7,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 10,
      "name": "PVT KORATA",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 11,
      "name": "PVT YUMANI",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 12,
      "name": "PVT FUJITA",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 2,
      "points": 7,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 13,
      "name": "PVT FUSANO",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 14,
      "name": "PVT YORIDO",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 4,
      "points": 13,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 15,
      "name": "PVT ISISHI",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 16,
      "name": "PFC ASHIGAWA",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Type 92",
      "breakdown": 6,
      "fp_range_0": 6,
      "fp_range_1": 7,
      "fp_range_2": 8,
      "fp_range_3": 9,
      "fp_range_4": 10,
      "fp_range_5": 11,
      "weapon_details": {
        "type": "MMG",
        "sustained_fp_0": 3,
        "sustained_fp_1": 4,
        "sustained_fp_2": 4,
        "sustained_fp_3": 5,
        "sustained_fp_4": 5,
        "sustained_fp_5": 6,
        "no_moving_fire": true
      },
      "morale": 4,
      "points": 79,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. 2 Men to Move. ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 17,
      "name": "PFC YAMASHIRA",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Type 93",
      "breakdown": 6,
      "fp_range_0": null,
      "fp_range_1": null,
      "fp_range_2": null,
      "fp_range_3": null,
      "fp_range_4": null,
      "fp_range_5": 12,
      "weapon_details": {
        "type": "Flamethrower",
        "range": 5,
        "fp": 12,
        "no_def_tem": true,
        "no_ff_inf_bonus": true,
        "moving_fire_not_halved": true
      },
      "morale": 4,
      "points": 55,
      "kia_unpinned": 7,
      "panic": 4,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 8,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 18,
      "name": "PVT IKADO",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 5,
      "points": 17,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 7 / BERSERK: (RR5) 0r RNC <= 7"
    },
    {
      "num": 19,
      "name": "PFC KOMOTO",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Shiki Kikanshoju Type 100",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
        "type": "Machine Pistol"
      },
      "morale": 3,
      "points": 12,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "AVAILABLE: 1944-1945; Airborne. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 20,
      "name": "PVT SHOBURO",
      "card_type": "Man",
      "ccv_unpinned_armed": 11,
      "ccv_unpinned_unarmed": 6,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 6,
      "points": 20,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 7,
      "ccv_pinned_unarmed": 2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 8 / BERSERK: (RR5) 0r RNC <= 8"
    },
    {
      "num": 21,
      "name": "SGT KODU",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": true,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 5,
      "points": 42,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity. ROUT: 0r RNC > 7 / BERSERK: (RR5) 0r RNC <= 7"
    },
    {
      "num": 22,
      "name": "PVT ICHIKI",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Model 89 Knee Mortar",
      "breakdown": 6,
      "morale": 3,
      "points": 41,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "weapon_details": {
        "type": "Mortar",
        "effect_number": 1,
        "alternate_effect_number": 3,
        "to_hit_ranges": ["1 [3]", "0 [1]", "0-1 [0]", "0-2 [0-1]", "0-3 [0-2]", null],
        "fp_ranges": [2, 2, 2, 1, 1, null],
        "no_moving_fire": true
      },
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 23,
      "name": "PVT YUMANA",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Model 89 Knee Mortar",
      "breakdown": 6,
      "morale": 4,
      "points": 54,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "weapon_details": {
        "type": "Mortar",
        "effect_number": 1,
        "alternate_effect_number": 3,
        "to_hit_ranges": ["1 [3]", "0 [1]", "0-1 [0]", "0-2 [0-1]", "0-3 [0-2]", null],
        "fp_ranges": [2, 2, 2, 1, 1, null],
        "no_moving_fire": true
      },
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 24,
      "name": "PVT YORUBA",
      "card_type": "Man",
      "ccv_unpinned_armed": 2,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Model 89 Knee Mortar",
      "breakdown": 6,
      "morale": 2,
      "points": 27,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": -2,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "weapon_details": {
        "type": "Mortar",
        "effect_number": 1,
        "alternate_effect_number": 3,
        "to_hit_ranges": ["1 [3]", "0 [1]", "0-1 [0]", "0-2 [0-1]", "0-3 [0-2]", null],
        "fp_ranges": [2, 2, 2, 1, 1, null],
        "no_moving_fire": true
      },
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 25,
      "name": "CPL KYOTO",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": true,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 4,
      "points": 33,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity if SL. ROUT: 0r RNC > 6 / BERSERK: (RR5) 0r RNC <= 6"
    },
    {
      "num": 26,
      "name": "PVT SAKATA",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Arisaka Meiji 38",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 2,
      "points": 7,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 27,
      "name": "PFC TENRYU",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Shiki Kikikanju Type 96",
      "breakdown": 6,
      "fp_range_0": 2,
      "fp_range_1": 3,
      "fp_range_2": 4,
      "fp_range_3": 5,
      "fp_range_4": 6,
      "fp_range_5": 6,
      "weapon_details": {
        "type": "LMG"
      },
      "morale": 3,
      "points": 35,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 28,
      "name": "PFC OI",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Model 97",
      "breakdown": 6,
      "morale": 3,
      "points": 17,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "weapon_details": {
        "type": "Anti-Tank Rifle",
        "effect_number": 0,
        "alternate_effect_number": 2,
        "to_hit_ranges": ["1 [2]", "0 [1]", "0 [1]", "0-1 [0]", "0-1 [0]", "0-2 [0-1]"],
        "fp_ranges": [1, 1, 1, 1, 1, 1],
        "flank_bonus": -1,
        "no_moving_fire": true
      },
      "notes": "No Secondary Weapons Allowed. 2 Men to Move. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 29,
      "name": "37mm Type 94",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 163,
      "kia_unpinned": 9,
      "panic": 5,
      "panic_pinned": 3,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": null,
      "weapon_details": {
        "type": "AT Gun",
        "effect_number": 1,
        "alternate_effect_number": 1,
        "breakdown": 6,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. ROUT: 0r RNC > 7 / BERSERK: (RR5) 0r RNC <= 7"
    },
    {
      "num": 30,
      "name": "47mm Type 1",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 193,
      "kia_unpinned": 9,
      "panic": 5,
      "panic_pinned": 3,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": null,
      "weapon_details": {
        "type": "AT Gun",
        "effect_number": 2,
        "alternate_effect_number": 2,
        "breakdown": 6,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. ROUT: 0r RNC > 7 / BERSERK: (RR5) 0r RNC <= 7"
    },
    {
      "num": 31,
      "name": "Type 97 TE-KE (Button Up)",
      "card_type": "Vehicle",
      "ovr": null,
      "ce": null,
      "button_up": true,
      "bog": "9/w9",
      "morale": 5,
      "points": 253,
      "armor": "i1/s2/k3",
      "flank": "i-2/s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [1, 2, 2, 3, 3, 4]
      },
      "notes": ""
    },
    {
      "num": 31,
      "name": "Type 97 TE-KE (CE)",
      "card_type": "Vehicle",
      "ovr": null,
      "ce": 9,
      "button_up": false,
      "bog": "0/w0",
      "morale": 5,
      "points": 253,
      "armor": "i1/s2/k3",
      "flank": "i-2/s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2, 3, 4, 5, 6, 7]
      },
      "notes": ""
    },
    {
      "num": 32,
      "name": "Type 95 KHA-GO (OVR 1)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "7/w9",
      "morale": 5,
      "points": 245,
      "armor": "i:s0/k1",
      "flank": "i-2/s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [1, 2, 2, 3, 3, 4]
      },
      "notes": ""
    },
    {
      "num": 32,
      "name": "Type 95 KHA-GO (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "8/w0",
      "morale": 5,
      "points": 245,
      "armor": "i:s0/k1",
      "flank": "i-2/s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2, 3, 4, 5, 6, 7]
      },
      "notes": ""
    },
    {
      "num": 33,
      "name": "Type 97 SHINHOTO CHI-HA (OVR 1)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "6/w9",
      "morale": 5,
      "points": 305,
      "armor": "i1/s2/k3",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 2,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [1, 2, 2, 3, 3, 4]
      },
      "notes": ""
    },
    {
      "num": 33,
      "name": "Type 97 SHINHOTO CHI-HA (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "7/w0",
      "morale": 5,
      "points": 305,
      "armor": "i1/s2/k3",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 2,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2, 3, 4, 5, 6, 7]
      },
      "notes": ""
    },
    {
      "num": 34,
      "name": "Type 3 CHI-NU (OVR 1)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "6/w9",
      "morale": 5,
      "points": 399,
      "armor": "i2/s3/k4",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [1, 2, 2, 3, 3, 4]
      },
      "available": "1943",
      "notes": ""
    },
    {
      "num": 34,
      "name": "Type 3 CHI-NU (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "7/w0",
      "morale": 5,
      "points": 399,
      "armor": "i2/s3/k4",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2, 3, 4, 5, 6, 7]
      },
      "notes": ""
    },
    {
      "num": 35,
      "name": "Type 1 SP HO-NI 1",
      "card_type": "Vehicle",
      "ovr": null,
      "ce": 9,
      "button_up": true,
      "bog": "7/w0",
      "morale": 5,
      "points": 269,
      "armor": "i1/s2/k3",
      "flank": "i-2/s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "alternate_effect_number": 5,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2, 3, 4, 5, 6, 7],
        "no_moving_fire": true
      },
      "available": "1943",
      "notes": "Pinned requires Rally 3. +1 To Hit vs Moving Target. +2 To Hit if Bogged / Immobilized."
    },
    {
      "num": 36,
      "name": "Type 92 AC OSAKA (OVR 1)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "2/w6",
      "morale": 5,
      "points": 118,
      "armor": "i:s-1/k0",
      "flank": "i-2/s-1/k0",
      "mg_breakdown": 6,
      "mg_fp_ranges": [2, 3, 3, 4, 4, 5],
      "notes": ""
    },
    {
      "num": 36,
      "name": "Type 92 AC OSAKA (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "3/w7",
      "morale": 5,
      "points": 118,
      "armor": "i:s-1/k0",
      "flank": "i-2/s-1/k0",
      "mg_breakdown": 6,
      "mg_fp_ranges": [3, 4, 5, 6, 7, 8],
      "notes": ""
    },
    {
      "num": 37,
      "name": "Type 1 HT HO-HA",
      "card_type": "Vehicle",
      "ovr": null,
      "ce": null,
      "button_up": null,
      "bog": null,
      "morale": 5,
      "points": null,
      "armor": "i:s-1/k0",
      "flank": "i-2/s-1/k0",
      "breakdown": null,
      "mg_breakdown": null,
      "notes": "Pinned requires Rally 3. Full stats not available on provided card."
    },
    {
      "num": 38,
      "name": "Type 97 CHI-HA (OVR 1)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "6/w9",
      "morale": 5,
      "points": 294,
      "armor": "i1/s2/k3",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "alternate_effect_number": 2,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [1, 2, 2, 3, 3, 4]
      },
      "notes": ""
    },
    {
      "num": 38,
      "name": "Type 97 CHI-HA (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "7/w0",
      "morale": 5,
      "points": 294,
      "armor": "i1/s2/k3",
      "flank": "i-1/s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "alternate_effect_number": 2,
        "to_hit_ranges": ["1", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "fp_ranges": [2, 3, 4, 5, 6, 7]
      },
      "notes": ""
    }
  ]
};