window.russiaData = {
  "name": "Russia",
  "hand_capacity": 4,
  "discard": "any",
  "discard_condition_no_action": true,
  "notes": "May discard any number of cards on Player.",
  "broken_squad": 50,
  "units": [
    {
      "num": 1,
      "name": "SGT ROSTOV",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": true,
      "asl": false,
      "weapon": "Tokarev SVT-40",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 4,
      "points": 40,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "Reduced Hand Capacity."
    },
    {
      "num": 2,
      "name": "Jr SGT BURLAK",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": true,
      "weapon": "DP 1928",
      "breakdown": 6,
      "fp_range_0": 3,
      "fp_range_1": 4,
      "fp_range_2": 5,
      "fp_range_3": 6,
      "fp_range_4": 7,
      "fp_range_5": 8,
       "weapon_details": {
           "type": "LMG",
           "sustained_fp_0": 2,
           "sustained_fp_1": 2,
           "sustained_fp_2": 3,
           "sustained_fp_3": 3,
           "sustained_fp_4": 4,
           "sustained_fp_5": 4
       },
      "morale": 4,
      "points": 67,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5,
      "notes": "Reduced Hand Capacity if SL. No Secondary Weapons Allowed."
    },
    {
      "num": 3,
      "name": "PVT PETROVSKY",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 5,
      "points": 15,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": 5
    },
    {
      "num": 4,
      "name": "PVT YASTREBOFT",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 4,
      "points": 12,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 4
    },
    {
      "num": 5,
      "name": "PVT STORCHILLO",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 9,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 3
    },
    {
      "num": 6,
      "name": "PVT SOLOVIEV",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4
    },
    {
      "num": 7,
      "name": "PVT KRISTOV",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 9,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 3
    },
    {
      "num": 8,
      "name": "PVT CHERNENKO",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 5,
      "points": 15,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": 5
    },
    {
      "num": 9,
      "name": "PVT NOSENKO",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 2,
      "points": 6,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 2
    },
    {
      "num": 10,
      "name": "PVT KVASNIKOV",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 1,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 1,
      "points": 4,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -3,
      "kia_pinned": 9,
      "rout": 2
    },
    {
      "num": 11,
      "name": "PVT SOKOLOFF",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 2,
      "points": 7,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 3
    },
    {
      "num": 12,
      "name": "PVT VAKUTA",
      "card_type": "Man",
      "ccv_unpinned_armed": 10,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 5,
      "points": 17,
      "kia_unpinned": 8,
      "panic": 6,
      "ccv_pinned_armed": 6,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": 6
    },
    {
      "num": 13,
      "name": "PVT ZAHAROFF",
      "card_type": "Man",
      "ccv_unpinned_armed": 9,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 4,
      "points": 14,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 5,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 5
    },
    {
      "num": 14,
      "name": "PVT ZAYAKOV",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 2,
      "points": 6,
      "kia_unpinned": 8,
      "panic": 2,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": 2
    },
    {
      "num": 15,
      "name": "PVT UIHAILOFT",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "Mosin Nagant M1891/30",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 1,
      "fp_range_3": 2,
      "fp_range_4": 2,
      "fp_range_5": 3,
      "morale": 3,
      "points": 10,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4
    },
    {
      "num": 16,
      "name": "CPL SEMENOV",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "Maxim PM 1910",
      "breakdown": 6,
      "fp_range_0": 6,
      "fp_range_1": 7,
      "fp_range_2": 8,
      "fp_range_3": 9,
      "fp_range_4": 10,
      "fp_range_5": 11,
       "weapon_details": {
           "type": "MMG",
           "sustained_fp_0": 3,
           "sustained_fp_1": 4,
           "sustained_fp_2": 4,
           "sustained_fp_3": 5,
           "sustained_fp_4": 5,
           "sustained_fp_5": 6,
           "no_moving_fire": true
       },
      "morale": 4,
      "points": 69,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 4,
      "notes": "No Secondary Weapons Allowed. No Moving Fire."
    },
    {
      "num": 17,
      "name": "CPL KIRILENKO",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "ROKS-2",
      "breakdown": 6,
      "fp_range_0": null,
      "fp_range_1": null,
      "fp_range_2": null,
      "fp_range_3": null,
      "fp_range_4": null,
      "fp_range_5": 12,
       "weapon_details": {
           "type": "Flamethrower",
           "range": 5,
           "fp": 12,
           "no_def_tem": true,
           "no_ff_inf_bonus": true,
           "moving_fire_not_halved": true
       },
      "morale": 4,
      "points": 48,
      "kia_unpinned": 7,
      "panic": 4,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 8,
      "rout": 4,
      "notes": "No Def TEM, No FF/INF Bonus. Moving Fire Not Halved. No Secondary Weapons Allowed."
    },
    {
      "num": 18,
      "name": "PVT MIHAILOFT",
      "card_type": "Man",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "PTRS 41",
      "breakdown": 6,
      "fp_range_0": 1,
      "fp_range_1": 1,
      "fp_range_2": 1,
      "fp_range_3": 1,
      "fp_range_4": 1,
      "fp_range_5": 1,
      "weapon_details": {
           "type": "Anti-Tank Rifle",
           "effect": 0,
           "to_hit_range_0": 5,
           "to_hit_range_1": 4,
           "to_hit_range_2": 4,
           "to_hit_range_3": 3,
           "to_hit_range_4": 3,
           "to_hit_range_5": 2,
           "flank_bonus": -1,
           "no_moving_fire": true
       },
      "morale": 3,
      "points": 12,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 4,
      "notes": "No Secondary Weapons Allowed. No Moving Fire."
    },
    {
      "num": 19,
      "name": "COMM DOTTSKI",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "PPSh 41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
       "weapon_details": {
           "type": "Machine Pistol",
           "group_bonus": "Morale +1; Pinned, check RPN"
       },
      "morale": 3,
      "points": 33,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": 3,
      "notes": "Reduced Hand Capacity if SL. Available : 1941 - 10/1942."
    },
    {
      "num": 20,
      "name": "PVT KNEZEVICH",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "PPSh 41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "morale": 4,
      "points": 14,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": 4
    },
    {
      "num": 21,
      "name": "Jr SGT ALIEV",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": true,
      "weapon": "PPSh 41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
        "type": "Machine Pistol"
      },
      "morale": 3,
      "points": 32,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity if SL. ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 22,
      "name": "PVT IGORSKI",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "PPSh 41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
        "type": "Machine Pistol"
      },
      "morale": 3,
      "points": 12,
      "kia_unpinned": 8,
      "panic": 4,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 4 / BERSERK: (RR5) 0r RNC <= 4"
    },
    {
      "num": 23,
      "name": "PVT PODGORNY",
      "card_type": "Man",
      "ccv_unpinned_armed": 7,
      "ccv_unpinned_unarmed": 4,
      "sl": false,
      "asl": false,
      "weapon": "PPSh 41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
        "type": "Machine Pistol"
      },
      "morale": 4,
      "points": 17,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 3,
      "ccv_pinned_unarmed": 0,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 24,
      "name": "PVT BAIBAKOV",
      "card_type": "Man",
      "ccv_unpinned_armed": 6,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "PPSh 41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
        "type": "Machine Pistol"
      },
      "morale": 3,
      "points": 11,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 2,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 25,
      "name": "PVT KORNIEV",
      "card_type": "Man",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 2,
      "sl": false,
      "asl": false,
      "weapon": "PPSh 41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
        "type": "Machine Pistol"
      },
      "morale": 2,
      "points": 8,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": -2,
      "kia_pinned": 9,
      "rout": null,
      "notes": "ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 26,
      "name": "SGT ZORIN",
      "card_type": "Man",
      "ccv_unpinned_armed": 8,
      "ccv_unpinned_unarmed": 5,
      "sl": true,
      "asl": false,
      "weapon": "PPSh 41",
      "breakdown": 6,
      "fp_range_0": 0,
      "fp_range_1": 0,
      "fp_range_2": 0,
      "fp_range_3": 1,
      "fp_range_4": 3,
      "fp_range_5": 5,
      "weapon_details": {
        "type": "Machine Pistol"
      },
      "morale": 5,
      "points": 43,
      "kia_unpinned": 8,
      "panic": 5,
      "ccv_pinned_armed": 4,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "Reduced Hand Capacity if SL. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 27,
      "name": "CPL SYMSILOV",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 3,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "morale": 3,
      "points": 33,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": -1,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "weapon_details": {
        "type": "Mortar",
        "name": "50mm Mortar",
        "effect_number": 2,
        "breakdown": 6,
        "to_hit_ranges": [1, "0-1", "0-2", "0-3", null, null],
        "he_fp_ranges": [3, 1, 0, "0-1", 1, 2],
        "no_moving_fire": true
      },
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 28,
      "name": "CPL BORISOFT",
      "card_type": "Man",
      "ccv_unpinned_armed": 4,
      "ccv_unpinned_unarmed": 3,
      "sl": false,
      "asl": false,
      "weapon": "DP 1928",
      "breakdown": 6,
      "fp_range_0": 3,
      "fp_range_1": 4,
      "fp_range_2": 5,
      "fp_range_3": 6,
      "fp_range_4": 7,
      "fp_range_5": 8,
      "weapon_details": {
        "type": "LMG",
        "sustained_fp_0": 2,
        "sustained_fp_1": 2,
        "sustained_fp_2": 3,
        "sustained_fp_3": 3,
        "sustained_fp_4": 4,
        "sustained_fp_5": 4
      },
      "morale": 3,
      "points": 30,
      "kia_unpinned": 8,
      "panic": 3,
      "ccv_pinned_armed": 0,
      "ccv_pinned_unarmed": -1,
      "kia_pinned": 9,
      "rout": null,
      "notes": "No Secondary Weapons Allowed. ROUT: 0r RNC > 3 / BERSERK: (RR5) 0r RNC <= 3"
    },
    {
      "num": 29,
      "name": "45mm M32",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 170,
      "kia_unpinned": 9,
      "panic": 5,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": null,
      "weapon_details": {
        "type": "AT Gun",
        "effect_number": 2,
        "breakdown": 6,
        "to_hit_ranges": ["0", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 30,
      "name": "57mm M43",
      "card_type": "Weapon",
      "ccv_unpinned_armed": 5,
      "ccv_unpinned_unarmed": 5,
      "sl": false,
      "asl": false,
      "morale": 5,
      "morale_pinned": 3,
      "points": 187,
      "kia_unpinned": 9,
      "panic": 5,
      "ccv_pinned_armed": 1,
      "ccv_pinned_unarmed": 1,
      "kia_pinned": 7,
      "rout": null,
      "weapon_details": {
        "type": "AT Gun",
        "effect_number": 2,
        "alternate_effect_number": 4,
        "breakdown": 6,
        "to_hit_ranges": ["0", "0-1", "0-2", "0-3", "0-4", "0-5"],
        "no_moving_fire": true
      },
      "notes": "Pinned requires Rally 3. ROUT: 0r RNC > 5 / BERSERK: (RR5) 0r RNC <= 5"
    },
    {
      "num": 31,
      "name": "M5 HALFTACK",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": 9,
      "button_up": false,
      "bog": "4/w7",
      "morale": 5,
      "points": 137,
      "armor": "i:s-1/k0",
      "flank": "i:-2/s-1/k0",
      "mg_breakdown": 6,
      "mg_fp_ranges": [7, 8, 9, 10, 11, 12],
      "available": "1943-1945",
      "notes": "Pinned requires Rally 3."
    },
     {
      "num": 32,
      "name": "BA-6",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "2/w6",
      "morale": 5,
      "points": 187,
      "armor": "i:s-1/k0",
      "flank": "i:-2/s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "ranged_firepower_combined": [
          { "to_hit": null, "fp": 2 },
          { "to_hit": "1", "fp": 3 },
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 6 },
          { "to_hit": "0-3", "fp": 7 }
        ]
      },
      "available": "1941-1942",
      "notes": ""
    },
    {
      "num": 32,
      "name": "BA-6 (OVR 1)",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "1/w5",
      "morale": 5,
      "points": 187,
      "armor": "i:s-1/k0",
      "flank": "i:-2/s-1/k0",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "ranged_firepower_combined": [
          { "to_hit": "3", "fp": 2 },
          { "to_hit": "1", "fp": 3 },
          { "to_hit": "0", "fp": 3 },
          { "to_hit": "0-1", "fp": 4 },
          { "to_hit": "0-2", "fp": 4 },
          { "to_hit": "0-3", "fp": 5 }
        ]
      },
      "available": "1941-1942",
      "notes": ""
    },
    {
      "num": 33,
      "name": "T-26S",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "9/w9",
      "morale": 5,
      "points": 288,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": "3", "fp": 2 },
          { "to_hit": "1", "fp": 3 },
          { "to_hit": "0", "fp": 3 },
          { "to_hit": "0-1", "fp": 4 },
          { "to_hit": "0-2", "fp": 4 },
          { "to_hit": "0-3", "fp": 5 }
        ]
      },
      "available": "1941-1942",
      "notes": ""
    },
    {
      "num": 33,
      "name": "T-26S (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "0/w0",
      "morale": 5,
      "points": 288,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": null, "fp": 2 },
          { "to_hit": "0-1", "fp": 3 },
          { "to_hit": "0-2", "fp": 4 },
          { "to_hit": "0-3", "fp": 5 },
          { "to_hit": "0-4", "fp": 6 },
          { "to_hit": "0-5", "fp": 7 }
        ]
      },
      "available": "1941-1942",
      "notes": ""
    },
    {
      "num": 34,
      "name": "T-34B",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": null,
      "button_up": true,
      "bog": "9/w9",
      "morale": 5,
      "points": 429,
      "armor": "i5/s6/k7",
      "flank": "i3/s4/k5",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "ranged_firepower_combined": [
          { "to_hit": "3", "fp": 3 },
          { "to_hit": "1", "fp": 4 },
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 5 },
          { "to_hit": "0-3", "fp": 6 }
        ]
      },
      "available": "JULY 1941",
      "notes": "Pinned requires Rally 3"
    },
    {
      "num": 34,
      "name": "T-34B (OVR 3)",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": 9,
      "button_up": false,
      "bog": "0/w0",
      "morale": 5,
      "points": 429,
      "armor": "i5/s6/k7",
      "flank": "i3/s4/k5",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 6 },
          { "to_hit": "0-3", "fp": 7 },
          { "to_hit": "0-4", "fp": 8 },
          { "to_hit": "0-5", "fp": 9 }
        ]
      },
      "available": "JULY 1941",
      "notes": "Pinned requires Rally 3"
    },
    {
      "num": 35,
      "name": "T34-85",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": 9,
      "button_up": false,
      "bog": "8/w0",
      "morale": 5,
      "points": 449,
      "armor": "i5/s6/k7",
      "flank": "i3/s4/k5",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 5,
        "ranged_firepower_combined": [
          { "to_hit": "0", "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 6 },
          { "to_hit": "0-3", "fp": 7 },
          { "to_hit": "0-4", "fp": 8 },
          { "to_hit": "0-5", "fp": 9 }
        ]
      },
      "available": null,
      "notes": "Pinned requires Rally 3 (Inferred from other T-34 variant)"
    },
    {
      "num": 35,
      "name": "T34-85 (APRIL 1944)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": null,
      "button_up": true,
      "bog": "7/w9",
      "morale": 5,
      "points": 449,
      "armor": "i5/s6/k7",
      "flank": "i3/s4/k5",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 5,
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"],
        "fp_ranges": [4, 5, 6, 7, 8, 9]
      },
      "available": "APRIL 1944",
      "notes": "Pinned requires Rally 3"
    },
    {
      "num": 36,
      "name": "T-26S OT-133",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": null,
      "button_up": true,
      "bog": "6/w9",
      "morale": 5,
      "points": 198,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "flamethrower_details": {
        "type": "Flamethrower",
        "range": 4,
        "fp": 10,
        "no_def_tem": true,
        "no_ff_inf_bonus": true,
        "moving_fire_not_halved": true
      },
      "mg_fp_ranges": [2, 3, 4, 5, 6, 7],
      "available": "1941-1942",
      "notes": "No Defensive TEM, No FF Bonus, Moving Fire not Halved. Pinned requires Rally 3 (Inferred)"
    },
    {
      "num": 36,
      "name": "T-26S OT-133 (OVR 5)",
      "card_type": "Vehicle",
      "ovr": 5,
      "ce": 9,
      "button_up": true,
      "bog": "7/w0",
      "morale": 5,
      "points": 198,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "flamethrower_details": {
        "type": "Flamethrower",
        "range": 5,
        "fp": 14,
        "no_def_tem": true,
        "no_ff_inf_bonus": true,
        "moving_fire_not_halved": true
      },
      "mg_fp_ranges": [2, 3, 4, 5, 6, 7],
      "available": "1941-1942",
      "notes": "No Defensive TEM, No FF Bonus, Moving Fire not Halved. Pinned requires Rally 3 (Inferred)"
    },
    {
      "num": 37,
      "name": "BT-7-2",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "8/w9",
      "morale": 5,
      "points": 267,
      "armor": "i:s1/k2",
      "flank": "i:s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": "3", "fp": 2 },
          { "to_hit": "1", "fp": 3 },
          { "to_hit": "0", "fp": 3 },
          { "to_hit": "0-1", "fp": 4 },
          { "to_hit": "0-2", "fp": 4 },
          { "to_hit": "0-3", "fp": 5 }
        ]
      },
      "available": "1941",
      "notes": ""
    },
    {
      "num": 37,
      "name": "BT-7-2 (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": null,
      "button_up": true,
      "bog": "9/w0",
      "morale": 5,
      "points": 267,
      "armor": "i:s1/k2",
      "flank": "i:s0/k1",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": "3", "fp": 2 },
          { "to_hit": "1", "fp": 3 },
          { "to_hit": "0", "fp": 3 },
          { "to_hit": "0-1", "fp": 4 },
          { "to_hit": "0-2", "fp": 4 },
          { "to_hit": "0-3", "fp": 5 }
        ]
      },
      "available": "1941",
      "notes": ""
    },
    {
      "num": 38,
      "name": "SU-85",
      "card_type": "Vehicle",
      "ovr": null,
      "ce": 9,
      "button_up": true,
      "bog": "8/w0",
      "morale": 5,
      "points": 372,
      "armor": "i5/s6/k7",
      "flank": "i3/s4/k5",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 5,
        "fp_ranges": [1, "0-1", "0-2", "0-3", "0-4", "0-5"],
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"]
      },
      "available": "SEPTEMBER 1943",
      "notes": "No Moving Fire Allowed. +1 To Hit vs Moving Target. +2 To Hit if Bogged / Immobilized."
    },
    {
      "num": 39,
      "name": "IS-2",
      "card_type": "Vehicle",
      "ovr": 5,
      "ce": 9,
      "button_up": false,
      "bog": "8/w0",
      "morale": 5,
      "points": 563,
      "armor": "i8/s9/k10",
      "flank": "i5/s6/k7",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 6,
        "alternate_effect_number": 8,
        "fp_ranges": [8, 9, 10, 11, 12, 13],
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"]
      },
      "available": null,
      "notes": "Pinned requires Rally 3 (Inferred)"
    },
    {
      "num": 39,
      "name": "IS-2 (JULY 1944)",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": null,
      "button_up": true,
      "bog": "7/w9",
      "morale": 5,
      "points": 563,
      "armor": "i8/s9/k10",
      "flank": "i5/s6/k7",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 6,
        "alternate_effect_number": 8,
         "fp_ranges": [8, 9, 10, 11, 12, 13],
        "to_hit_ranges": ["3", "1", "0", "0-1", "0-2", "0-3"]
      },
      "available": "JULY 1944",
      "notes": "Pinned requires Rally 3"
    },
     {
      "num": 40,
      "name": "T-60",
      "card_type": "Vehicle",
      "ovr": 1,
      "ce": null,
      "button_up": true,
      "bog": "9/w9",
      "morale": 5,
      "points": 256,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "ranged_firepower_combined": [
          { "to_hit": "3", "fp": 2 },
          { "to_hit": "1", "fp": 3 },
          { "to_hit": "0", "fp": 3 },
          { "to_hit": "0-1", "fp": 4 },
          { "to_hit": "0-2", "fp": 4 },
          { "to_hit": "0-3", "fp": 5 }
        ]
      },
      "available": "OCTOBER 1941-1943",
      "notes": ""
    },
    {
      "num": 40,
      "name": "T-60 (OVR 2)",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": 9,
      "button_up": false,
      "bog": "0/w0",
      "morale": 5,
      "points": 256,
      "armor": "i1/s2/k3",
      "flank": "i0/s1/k2",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 1,
        "ranged_firepower_combined": [
          { "to_hit": null, "fp": 2 },
          { "to_hit": "0-1", "fp": 3 },
          { "to_hit": "0-2", "fp": 4 },
          { "to_hit": "0-3", "fp": 5 },
          { "to_hit": "0-4", "fp": 6 },
          { "to_hit": "0-5", "fp": 7 }
        ]
      },
      "available": "OCTOBER 1941-1943",
      "notes": ""
    },
     {
      "num": 41,
      "name": "T-28C",
      "card_type": "Vehicle",
      "ovr": 2,
      "ce": null,
      "button_up": true,
      "bog": "1/w9",
      "morale": 5,
      "points": 341,
      "armor": "i3/s4/k5",
      "flank": "i2/s3/k4",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "alternate_effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": "3", "fp": 4 },
          { "to_hit": "1", "fp": 5 },
          { "to_hit": "0", "fp": 5 },
          { "to_hit": "0-1", "fp": 6 },
          { "to_hit": "0-2", "fp": 6 },
          { "to_hit": "0-3", "fp": 7 }
        ]
      },
      "available": "1941",
      "notes": ""
    },
     {
      "num": 41,
      "name": "T-28C (OVR 3)",
      "card_type": "Vehicle",
      "ovr": 3,
      "ce": 9,
      "button_up": false,
      "bog": "2/w0",
      "morale": 5,
      "points": 341,
      "armor": "i3/s4/k5",
      "flank": "i2/s3/k4",
      "breakdown": 6,
      "mg_breakdown": 6,
      "weapon_details": {
        "type": "Main Gun",
        "effect_number": 4,
        "alternate_effect_number": 2,
        "ranged_firepower_combined": [
          { "to_hit": null, "fp": 4 },
          { "to_hit": "0-1", "fp": 5 },
          { "to_hit": "0-2", "fp": 6 },
          { "to_hit": "0-3", "fp": 7 },
          { "to_hit": "0-4", "fp": 8 },
          { "to_hit": "0-5", "fp": 10 }
        ]
      },
      "available": "1941",
      "notes": ""
    }
  ]
};